### ISSUE TITLE
Unable to use Geogetter Blueprint

### ISSUE THREAD

**Issue by skyprime17** [SuperGO2/supergo2-issues#102]
**Describe the bug**
Unable to use the GeoGetter(Blueprint) from instance 7 

**To Reproduce**
1. Have all the requirements researched(Valkyrie II)
2.Try to use the blueprint

**Screenshots**
![image](https://user-images.githubusercontent.com/57846375/177398811-97cba48b-b1b0-45d9-a004-5a9e93afbc3d.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0507b.closed-alpha` version.
