### ISSUE TITLE
Fleet cant be dimissed

### ISSUE THREAD

**Issue by ABanC1001** [SuperGO2/supergo2-issues#103]
**Describe the bug**
(I dont know how to reproduce it, it just happened to me) When I tried to dimiss one of my biggest fleet, it didn't show the right commander, also I couldn't dimiss the fleet,

**Expected behavior**
It should just be dimissed after click on it, also it should show anna instead of angla

**Comment by ToxicSSJ** [comment]
This bug happens because there is a problem with the ID of everything in general. So fixing this bug will be a pretty big problem. I hope I can solve it soon.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1107a.closed-alpha` version. **EXPERIMENTAL SOLUTION**
