### ISSUE TITLE
Science > Free Trade 1 cannot be completed

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#106]
Science > Free Trade 1 cannot be completed.
<img width="492" alt="FreeTradenowork" src="https://user-images.githubusercontent.com/102439239/177434181-54877294-ee3e-40f9-bff0-3496808aa82f.png">

**Comment by StarfishPrime-1** [comment]
For the record the very first *trade* I did was sell a bugged ship. <im working on that as well

**Comment by ToxicSSJ** [comment]
Have you tested this after `V2022.0507b.closed-alpha`?

**Comment by StarfishPrime-1** [comment]
Yes It was completed when the server was back up!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
