### ISSUE TITLE
Science > Construction Speedup cannot be completed

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#107]
Science > Construction Speedup cannot be completed

<img width="491" alt="Construction speedup" src="https://user-images.githubusercontent.com/102439239/177437728-343a6fa9-156b-4118-bd45-1a9ae31cb66c.png">

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
