### ISSUE TITLE
Subsidiary territory > Harvest

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#108]
Subsidiary territory > Harvesting should max out at 4 I believe
<img width="473" alt="harvest 5" src="https://user-images.githubusercontent.com/102439239/177438200-c5e8ab02-9068-4acd-b89f-a3bed6ba1e69.png">
5

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
