### ISSUE TITLE
I6: escudos negadores no reducen el daño

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#111]
**Describe the bug**
  Pareciera que es imposible no tomar daño de las naves del catalogo palenke con sumo laser,
no importa cuantos negadores tenga el diseño ni cuantas naves por stack alla
En el primer video muestro como tres diseños diferentes de azotes, uno tanke con full heat diffusion, 
otro offtank, con heat difussions y pulsar laser , y otro con solo energy shields reciben el mismo daño
este daño ronda los 50k - 70k segun la cantidad de naves atacantes y la posicion
https://drive.google.com/file/d/10nVPQQjKbFcbmNoGZeh3L68JAb5ZYTSm/view?usp=sharing

En el segundo video es para contemplarlo mejor, mismo diseño, diferente cantidad de naves por slot siempre tomaran 50k de daño aproximadamente
https://drive.google.com/file/d/1pO9sj-hPvlWuSbBsb36fmVvKVvpRySra/view?usp=sharing

**Comment by Tuni67** [comment]
So the damage reduction of the particle and heat shield doesnt work it seems. That would explain why my ships sucked -.-

**Comment by Colorap8** [comment]
They work badly but I don't know what the exact error is, in arena the deniers work perfectly

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
