### ISSUE TITLE
No se activa la pasiva del comandante "Titan"

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#116]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Hola, es importante que sigas con el formato y rellenes con información cada subtitulo si es aplicable para darle pronta solución al problema. En este caso ningún comandante tiene habilidades funcionando, asi que no se trata de un bug si no de una funcionalidad no implementada aún.
