### ISSUE TITLE
Missile Weapon [Scientific Researches]

### ISSUE THREAD

**Issue by ToxicSSJ** [SuperGO2/supergo2-issues#118]
**Missile Science Progression:**

- [x] Missile Theory
- [x] Missile Accuracy
- [x] Cruise Dynamics
- [x] Missile Research
- [x] Multidirectional Assault
- [x] Missile Elusion
- [x] Missile Space Optimization
- [x] Missile Concussion
- [x] Sharpnel Research
- [x] Exaltation
- [x] Supression
- [x] Nuclear Radiation Research
- [x] Break Armor
- [x] Energy Conservation
- [x] Rapid Loading
- [x] Perfect Storm

**Comment by Tuni67** [comment]
Missile Space Optimization is already implemented.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0108a.closed-alpha` version.
