### ISSUE TITLE
Problema de ez reward

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#120]
**Describe the bug** 
no me dio la recompensa de los cheques en ez reward
se salteo premios y aparecio luego del de 30 minutos paso a 2h

**Screenshots**
![3](https://user-images.githubusercontent.com/108841838/177671004-a62d49cc-88ba-4ff3-87c3-f245ed3bb3bd.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1407a.closed-alpha` version.
