### ISSUE TITLE
Pierce tech 

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#121]
**Describe the bug**
Pierce tech doesnt reduce shields first 100% of the time

**To Reproduce**
1. Tech pierce 
2. Go to a instance
3. Observe that when a fleet hits enemy ships, sometimes there is -2 shields removed from them multiple times

**Expected behavior**
All shields should be removed before dealing damage to the hull

**Screenshots**
![2022-07-07](https://user-images.githubusercontent.com/102363858/177746057-54db66fd-cec8-4757-b1bc-5bd1bfd18198.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1007a.closed-alpha` version.
