### ISSUE TITLE
resetting cards bug

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#123]
**Describe the bug**
after finishing resetting cards they still appearing in my bag , and cant use cuz they should be zero , they disappearing after refresh 

**To Reproduce**
1. Go to command center
2. Click on commander and reset 
3. Scroll down to bag after resetting cards finish 
4. See error , you still have cards but cant use , disappearing after refresh 

**Expected behavior**
resetting cards should be zero after done resetting 

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
