### ISSUE TITLE
side quest raising morale 11 unclaimable 

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#124]
**Describe the bug**
side quest - raising morale not claimable

**To Reproduce**
1. Go to tutorial
2. Click on enter quest 
3. Scroll down to side quest then find raising morale 11
4. See error i cant claim the prize , even i achieve it by ss check 

**Expected behavior**
should be claimable 

**Screenshots**

![raising morale](https://user-images.githubusercontent.com/108695969/177791373-6f2857f6-012e-4602-939d-9fb2727f25bd.png)

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
