### ISSUE TITLE
voucher received before cooldown finished

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#125]
**Describe the bug**
the voucher gained from subsidiary territory received before cooldown finish 

**To Reproduce**
1. Go to my tools 
2. Click on subsidiary territory
3. Scroll down to claim voucher
4. See error vouchers can be claimed before the cooldown finish after friends making repair for space station 

**Expected behavior**
vouchers should be claimable after cooldown finish which it 24h 

**Screenshots**

![voucher](https://user-images.githubusercontent.com/108695969/177797448-2ede009f-fbee-46b1-bd0b-3fa180f4e92a.png)

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
