### ISSUE TITLE
Cant remove friends from friendlist

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#126]
**Describe the bug**
You cant remove friends from your friendlist. Nothing happens,

**To Reproduce**
1. Go to your friend list 
2. Click on a friend
3. Click on remove

**Expected behavior**
Friend gets removed

**Screenshots**
not really necessary.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
