### ISSUE TITLE
fleet target changed after instance 4 started 

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#128]
**Describe the bug**
fleet target changed after instance 4 started , i set max range max dur, after i4 started it became min range closet target

**To Reproduce**

**Expected behavior**

**Screenshots**
![i4](https://user-images.githubusercontent.com/108695969/177884962-82bf80eb-d892-4d64-ab65-8d0c8d81143e.png)

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1107a.closed-alpha` version.
