### ISSUE TITLE
Bug visual, desaparecen edificios

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#129]
**Describe the bug**
me meti en una mision y al clickear home todo aparecio sin edificios

**Screenshots**
![1](https://user-images.githubusercontent.com/108841838/177887301-16f63383-a3ae-4adc-a02e-eb040283f325.png)
![2](https://user-images.githubusercontent.com/108841838/177887316-b2f0ca81-e99c-452a-ba33-516ecc7de688.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0808a.closed-alpha` version.
