### ISSUE TITLE
Web Mall Purchasing 

### ISSUE THREAD

**Issue by DevTruce** [SuperGO2/supergo2-issues#13]
Description: unable to purchase voucher web mall items and a couple mall point items

How to reproduce: open the web mall and purchase mp/voucher item with vouchers or purchase a coupon/sp card using mp

Expected behavior: Prompt a successful purchase notification for the item, reduce player voucher or mp value and add the item to the players inventory 

Video: https://jmp.sh/Iq3bQ27

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0307a.closed-alpha` version.
