### ISSUE TITLE
Bug importante luego de cancelar una arena

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#132]
**Describe the bug**
crear una arena, luchar y aceptar cancelar la batalla 

**Screenshots**
![23e](https://user-images.githubusercontent.com/108841838/177898151-314b70af-dbe1-40e9-aff0-af95a06e4ed1.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
