### ISSUE TITLE
Unable to use Ship-baed air interception cabin bp

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#133]
**Describe the bug**
unable to use I8 blueprint based air interception

**To Reproduce**
Have all the requeriments to use , (Anti aircraft cannon II) and try use

**Screenshots**
![image](https://user-images.githubusercontent.com/108563861/177903279-b99b2f13-0f9d-4893-b220-1e1b42982c0a.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
