### ISSUE TITLE
Cant open corsair chest

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#135]
**Describe the bug**
Cant open the corsair chest from honor shop

**To Reproduce**
1. Go to the honor shop
2. Click on the corsair chest and buy 90 for 270 hp
3. Go to your inventory and try to open the chests

**Expected behavior**
Corsair chest will be opened and you can go and proceed to generate chips

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2507a.closed-alpha` version.
