### ISSUE TITLE
bug chip

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#137]
**Describe the bug**
No genera mas del chip del nivel 3
**To Reproduce**
1. Go to '...' generate bionic chip
2. Click on '....' automatic generate

**Expected behavior**
se espera que siga generando a partir del tercer nivel de chip pero se atasca todo
![Uploading chip.png…]()

**Screenshots**

**Additional context**

**Comment by Tuni67** [comment]
Here is a video regarding this issue

https://user-images.githubusercontent.com/108492773/177990325-47725b84-263a-4e5b-af38-76119ca42e2d.mp4

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2707a.closed-alpha` version.
