### ISSUE TITLE
0 Ships shown

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#139]
**Describe the bug**
If you bought ONE ship at the auction and sell it again it can happen that 0 ships are shown. Refer to screenshot.
**To Reproduce**

1. Go to auction house
2. buy 1 ship
3. place it in a fleet and then disband the fleet 
4. Sell the singular ship in AH
5. if you are unlucky you will see 0 ship

**Expected behavior**
Ship gets deleted from existence

**Screenshots**

![0shipbug](https://user-images.githubusercontent.com/108492773/178064115-02ced62a-4268-45e1-bde3-03a29eb86f89.JPG)

**Additional context**
ship was bought in a prior update, few days ago.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307a.closed-alpha` version.
