### ISSUE TITLE
Auction House Posting

### ISSUE THREAD

**Issue by Truce-R** [SuperGO2/supergo2-issues#14]
Description: unable to post more than one item to the auction house 

How to reproduce: open the auction house and try to post more than one item to the auction house

Expected behavior: you should be allowed to post multiple items to the auction house

Video: https://jmp.sh/fRKxR4h

**Comment by ToxicSSJ** [comment]
Fixed in `V2022.35b.beta-dev` now the limit is 30 (hardcoded).
