### ISSUE TITLE
side quest construction card

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#140]
**Describe the bug**
side quest construction card unclaimable

**To Reproduce**
1. Go tutorial 
2. Click on Enter quest 
3. Scroll down to side quest 
4. See error Time to build quest unclaimable 

**Expected behavior**
should be claimable after using construction crd

**Screenshots**

![construction card](https://user-images.githubusercontent.com/108695969/178066795-c5e3b150-fc0a-4ae2-acbb-44c61cdeb2b5.png)

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1007a.closed-alpha` version.
