### ISSUE TITLE
deletion of items in corp warehouse

### ISSUE THREAD

**Issue by AyartBeniYakubu** [SuperGO2/supergo2-issues#142]
**Describe the bug**

**To Reproduce**
1. corp storage
2. The items I have stored disappear when I re-login to the game.
3. The items I put in the warehouse disappear when I re-login to the game.
![3](https://user-images.githubusercontent.com/108958433/178077529-64bec881-76aa-4d86-b004-212a8ae1d3a6.png)
![4](https://user-images.githubusercontent.com/108958433/178077535-9b70fe9b-740d-4708-9986-fffeeb17294b.png)
![5](https://user-images.githubusercontent.com/108958433/178077539-8efc01a4-d942-4516-a287-83c3f8c1e409.png)

**Comment by AyartBeniYakubu** [comment]
![3](https://user-images.githubusercontent.com/108958433/178074818-729b8376-f751-4160-8bdb-98e498c898cb.png)
![4](https://user-images.githubusercontent.com/108958433/178074824-60147e2c-478f-405c-a493-76c5dcb714ba.png)
![5](https://user-images.githubusercontent.com/108958433/178074831-cc0919b2-f5a4-49f8-88eb-2a8fbede4b90.png)

**Comment by AyartBeniYakubu** [comment]
The items I put in the warehouse disappear when I re-login to the game.

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1007a.closed-alpha` version.
