### ISSUE TITLE
side quest commander card combination 

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#144]
Describe the bug
side quest commander card combination unclaimable

To Reproduce

Go tutorial
Click on Enter quest
Scroll down to side quest
See error commander card combination quest unclaimable

Expected behavior
should be claimable after combine cards

screen shoot
![card combination](https://user-images.githubusercontent.com/108695969/178083129-2e2f2d69-9cfc-46e8-b4cd-12f6a21e550b.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2207a.closed-alpha` version.
