### ISSUE TITLE
EZ rewards not resetting

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#146]
**Describe the bug**
If you dont get all EZ rewards from a single day, the game doesnt reset it during the midnight reset.

**To Reproduce**
1. Get some EZ rewards for the day
2. wait untill its past reset time
3. Get a new EZ reward and it should be the one from the previous day
4. If it was yesterday last one,  you cant use EZ rewards for the rest of the day

**Expected behavior**
EZ rewards should reset always during the resetting time, no matter if the player got all rewards or not

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1407a.closed-alpha` version.
