### ISSUE TITLE
Humaroid shown as Destroyed after beeing clicked on

### ISSUE THREAD

**Issue by zRulerr** [SuperGO2/supergo2-issues#147]
*not quite sure if this is a Bug, but the behaviour is not correct*

If you click on **any** Humaroid, it will change the sprite to the destroyed one.

**To Reproduce**
1. Click on Any humaroid
2. Observe

**Expected behavior**
Humaroid will be shown as describes above

**Screenshots**
![image](https://user-images.githubusercontent.com/108607807/178099035-a3080cff-a675-4a8f-be49-c614ee970a73.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2110a.closed-alpha` version.
