### ISSUE TITLE
MP set as 0 in the Login screen

### ISSUE THREAD

**Issue by zRulerr** [SuperGO2/supergo2-issues#148]
**Describe the bug**
Your MP is not displayed correctly in the ,,My Planets" Tab

**To Reproduce**
1. Start the client
2. Go to ,,My Planets"

**Expected behavior**
MP = 0

**Screenshots**
![image](https://user-images.githubusercontent.com/108607807/178099093-95f94fa3-20ff-45da-a7ed-05ece6d041c3.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0510a.closed-alpha` version.
