### ISSUE TITLE
Corps ranks in the list are the same throughout the pages

### ISSUE THREAD

**Issue by zRulerr** [SuperGO2/supergo2-issues#149]
**Describe the bug**
The Bug with the second coprs page was fixed, but now the ranks (Colonel, lt. Colonel etc) are same with every Page.
The First Person in the **First** Page is Colonel. The First person in the **Second** Page is also Colonel, and so on
**To Reproduce**

1. Go to "Social"
2. Go to "Corps"
3. Go to "Alpha Legends"
4. Click on "Alpha Legends"
5. View First and Second Page

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/108607807/178099346-dd59a776-bc5f-445b-b07f-3c4bd76db9fc.png)

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1207a.closed-alpha` version.
