### ISSUE TITLE
Research Disappearing

### ISSUE THREAD

**Issue by DevTruce** [SuperGO2/supergo2-issues#15]
Description: all research gets removed when the game is reloaded 

How to reproduce: open the research tab and research something, reload the game and go back to the research tab

Expected behavior: you should keep all learned research 

Video: https://jmp.sh/xfPjJn7

**Comment by Accone** [comment]
not implemented?

**Comment by Truce-R** [comment]
Yea, 2%. I believe I posted this issue before I reviewed the excel sheet. I was unsure in regards to removing it or not because of the 2%.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.606b.beta-dev` version.
