### ISSUE TITLE
Shipbuilding Mp speed up (old server)

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#150]
*this was on the old test server, Im just getting caught up lol. 

Mp speedup maxes out differently depending on ship Design

Speed up 5 different designs to the maximum. some allow 11 some 21 some30 and some 41

Maximum speedup should always be the same

<img width="524" alt="mp speed up" src="https://user-images.githubusercontent.com/102439239/178101119-b6ee244e-05b5-4a76-a6ac-311d09fb2ebf.png">

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2608a.closed-alpha` version.
