### ISSUE TITLE
side quest contribution 1 unclaimable

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#151]
Describe the bug
side quest contribution 1 unclaimable

To Reproduce

Go tutorial
Click on Enter quest
Scroll down to side quest
See error contribution 1 quest unclaimable

Expected behavior
should be claimable after contribute 100 points 

screen shoot 
![contribution1](https://user-images.githubusercontent.com/108695969/178117139-8398433e-8661-4efc-b28d-8a8233e4ac68.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1007a.closed-alpha` version.
