### ISSUE TITLE
Air defences modules : error when different weapons fire

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#152]
The air defences modules like "anti-aircraft cannon" or , "Fighter interception cabin" doesnot work well when the attack are multipleweapons example:
x19 Figther interception cabin can negate x9 ladybug, but a attacker with the same amount of weapons but diferents like x3 golem, x3 streamliner, x3 hunter, literaly destroy the ship
the same thing happen with missile weapons

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1007a.closed-alpha` version.
