### ISSUE TITLE
Auction bug bp didnt appear after selling !

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#153]
**Describe the bug**
after i posted "Hunter" Streamliner (Blueprint) , i couldnt find in the Auction , no one can see it unless u type in searching box in auction then you can see and buy it ,,,,

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Can't reproduce.

**Comment by StarfishPrime-1** [comment]
I purchased this bp from CUrvaSudMilano.  It was only searchable.  did not display in TC.  New bp's in the game would be searchable before they were implemented not that it matters

**Comment by ToxicSSJ** [comment]
Is too probably that this bug was caused by the ID issue. Check #103.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1207a.closed-alpha` version.
