### ISSUE TITLE
Module upgrade in dashboard is not updated after research cancel

### ISSUE THREAD

**Issue by irtusb** [SuperGO2/supergo2-issues#158]
**Describe the bug**
After a research is cancelled dashboard will stay with the last info it knew from before cancelling, or completed

**To Reproduce**
. Start a ship upgrade research (module upgrade not tested)
. Open Dashboard
. Close Dashboard
. Cancel research
. Open dashboard and research info will be there

**Screenshots**
here valkyrie has been cancelled, but still shows up
![cap](https://user-images.githubusercontent.com/300455/178127052-e2d3990b-0fd0-4cf1-b4ae-730c35bedfae.png)

**Comment by spectuu** [comment]
i cant reproduce that, and i think is only visual

**Comment by irtusb** [comment]
now I start to think that it was present in original as well

**Comment by ToxicSSJ** [comment]
This is not a bug, happened in the original client.
