### ISSUE TITLE
Merging Gems 

### ISSUE THREAD

**Issue by DevTruce** [SuperGO2/supergo2-issues#16]
Description: When merging gems if the game freezes and you try to re log, you will be unable to log back into the game servers until toxic performs a server reset  

How to reproduce: merge a large amount of gems, around 1000+  and re log/reload when the game freezes 

Expected behavior: you should be able to log in and load back into the server

![server](https://user-images.githubusercontent.com/85980370/160256130-64a5acf2-ae25-445c-8486-aa1f6aca97e1.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307a.closed-alpha` version.
