### ISSUE TITLE
Can't use antimatter engine bp

### ISSUE THREAD

**Issue by Zacmadness** [SuperGO2/supergo2-issues#162]
**Describe the bug**
When you use antimatter engine (after use combat engine it don't appear and don't consume it)

**To Reproduce**
1. Go to 'mall or got any antimatter engine'
2. Click on 'use'
3. Scroll down to 'you can see nothing happened'

**Expected behavior**
I bought an antimatter engine in the web mall for my ships design, after use it don't happened anything 

**Screenshots**
![Screenshot_2022-07-10-21-20-51-829_com cloudmosa puffinFree](https://user-images.githubusercontent.com/108496089/178171993-d55b3267-127b-45a7-ae67-facd8fb39177.jpg)

**Additional context**
I'm not sure if there's any another bp that can't be used but this one don't let me use the BP even having combat engine already

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1107a.closed-alpha` version.
