### ISSUE TITLE
Corp window glitches the game

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#163]
**Describe the bug**
If you open the corp window the game glitches out and you can no longer interact with anything. People can see your messages but you cant see their responses. Buying something from the shop, opening things in your inventory are no longer possible and building ships also doesnt work anymore. 

**To Reproduce**
1. Go to your corp
2. Click on your corp
4. See error of a blank corp window

**Expected behavior**
nothing should glitch out

**Screenshots**
![Notloading](https://user-images.githubusercontent.com/108492773/178260922-714e942f-5de7-4a7b-a30d-27a831ce4dc7.JPG)
![friendlist](https://user-images.githubusercontent.com/108492773/178260927-526aed8d-31ed-4f45-b7c6-9b42229543af.JPG)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1107a.closed-alpha` version.
