### ISSUE TITLE
Fallo de login

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#164]
**Describe the bug**
Pantalla negra

**To Reproduce**
Al abrir el cliente luego de algunas hora, la primera vez que abres aparece todo el interfaz en negro y debes volver a loguear
1. Cliente de sgo2 en el escritorio
2. abrir cliente, mi planeta, seleccionar planeta y PLAY
4. queda la pantalla negra hasta volver a iniciar

**Expected behavior**
Tendria que entrar directamente al juego sin necesidad de cerrar el cliente y volverlo a abrir

**Screenshots**

**Additional context**

**Comment by irtusb** [comment]
duplicate of #122
