### ISSUE TITLE
Can't Cross Merge Comms

### ISSUE THREAD

**Issue by zRulerr** [SuperGO2/supergo2-issues#165]
**Describe the bug**
When trying to crosss merge a commander to 3 Stars, the game freezes and the merge was not succesful

**To Reproduce**
1. Go to 'Compounding Center'
2. Click on 'Card merging'
3. Select Random CommanderS
4. Click on ,,Merge"
5. See error

**Expected behavior**
Game freezes, and merging was not succesfull (It didnt fail, so you still have those commanders)

**Screenshots**
![image](https://user-images.githubusercontent.com/108607807/178343914-5a6a2aa9-2418-40fc-b98c-89f9f46a5e9f.png)

![image](https://user-images.githubusercontent.com/108607807/178343953-90aa8406-eae7-4b0f-b563-60cfeedf4316.png)

You can see, how the grey tone in the second picture is ,,darker" than the grey in the picture above.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2207a.closed-alpha` version.
