### ISSUE TITLE
Trying to merge three commander card freezes the game

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#167]
**Describe the bug**
If you try to freeze 3 commander cards the game freezes. The bug seems to happen mostly after 2 Star Comms

**To Reproduce**
1. Go to Compounding Center
2. Click on Card Merge, then click on diffrent.
4. Sometimes the merge works and other times the game freezes.

**Expected behavior**
Comm. Card merges

**Comment by zRulerr** [comment]
Bug has already been reported. See bug #165 .

**Comment by Tuni67** [comment]
my bad
