### ISSUE TITLE
Merging Quadra gems freezes game

### ISSUE THREAD

**Issue by RockandTroll** [SuperGO2/supergo2-issues#169]
**Describe the bug**
When trying to merge Quadra gems (in my case, quadra dodge sapphire 1) the game freezes, similar to what happens when trying to merge 3 commanders Note (didnt seem to be an issue while merging the Guardian Triads)

**To Reproduce**

1. Go to compounding center
2. Go to Merging EX tab
3. Try to merge a Quadra Dodge Sapphire 1
4. Game will freeze

**Expected behavior**
Gems should merge

**Additional context**
Only seems to be an issue with Quadra's (for me anyway)

**Comment by RockandTroll** [comment]
TheLastKamikaze said its the same for Quadra Speed Emerald

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307a.closed-alpha` version.
