### ISSUE TITLE
Commander Merging

### ISSUE THREAD

**Issue by DevTruce** [SuperGO2/supergo2-issues#17]
Description: When merging commanders at some point it freezes on you and you are required to reload the game

How to reproduce: Merge commanders, it seems to pop the most around the 3*+ range, put a stack of about 30 or so 3*+ and begin merging, once the stack is complete it seems there is a relatively high chance for the game to fully freeze on you and requires a restart.

Expected behavior: you should be able to merge commanders without the game freezing

Video 1: https://jmp.sh/IEZSeGh
Video 2: https://jmp.sh/cnxPEgX 

Edit: I did more testing while uploading the videos and it seems to even freeze with less stacks, I did a couple 6s into 7s and the game reacted the same was as explained above

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2207a.closed-alpha` version.
