### ISSUE TITLE
ships do not use stability

### ISSUE THREAD

**Issue by irtusb** [SuperGO2/supergo2-issues#170]
**Describe the bug**
my ships are being destroyed even when receiving less damage than the stability gate

**To Reproduce**
. I have a shuttler II with gravity maint facility III (no tech). it has 3066 structure and 1.7 stability
. send this single ship to i1
. it is destroyed by the very first hit that damages structure

**Expected behavior**
stability raises (or lower) destruction gate by a certain factor. In this case the gate is at 1.7*3066 = _5212.2_ damage. It should only be destroyed upon receiving a hit higher than this gate. Or the slot being fully depleted of structure.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/300455/178861958-6574211f-b0a1-4171-aa71-b16cf8d8bae2.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2007a.closed-alpha` version.
