### ISSUE TITLE
Error in ship sale

### ISSUE THREAD

**Issue by AyartbeniYakub** [SuperGO2/supergo2-issues#173]
**Describe the bug**

**To Reproduce**
1.Error in ship sale

![Adsız2](https://user-images.githubusercontent.com/109309041/179058664-cbad093f-6eb2-486e-92e8-f4d05395b5aa.png)
![Adsız3](https://user-images.githubusercontent.com/109309041/179058675-0ef98b3c-0426-496e-ad17-54e25ff88adc.png)
![Adsız4](https://user-images.githubusercontent.com/109309041/179058682-e3a851ec-65a9-40f5-b4fb-5102f425a2ed.png)

**Comment by StarfishPrime-1** [comment]
@AyartbeniYakub did these have Planetary weapons installed?

**Comment by AyartbeniYakub** [comment]
No

16 Tem 2022 Cmt 23:49 tarihinde Jay ***@***.***> şunu yazdı:

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307a.closed-alpha` version.
