### ISSUE TITLE
quest

### ISSUE THREAD

**Issue by hito19** [SuperGO2/supergo2-issues#176]
solo puedo hacer misión 1 
![image](https://user-images.githubusercontent.com/65687925/179262700-e77f70e6-8c8b-440a-a703-2c7df0562f40.png)
![image](https://user-images.githubusercontent.com/65687925/179262778-5f04ae07-6a74-4265-ada1-635fb334df9a.png)

**Comment by skyprime17** [comment]
Same problem here

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2007a.closed-alpha` version.
