### ISSUE TITLE
Scatter is calculated wrong

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#177]
**Describe the bug**
It would seem like the scatter damage is being calculated by the possible raw damage what the attacking ships can give out, what is wrong.

**Expected behavior**
The amount of scatter damage should come from the damage actually inflicted to the enemy fleet, not the attack power of the ship what is shooting

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2007a.closed-alpha` version.
