### ISSUE TITLE
More than 1 flagship fleeted 

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#18]
Unique Title: Too many Flagships fleeted 
Description: Too many flagships  fleeted
How to reproduce: Create a fleet using any combination of the Tesla flagships. The huma flags and kazati and Principa are good
<img width="569" alt="flags" src="https://user-images.githubusercontent.com/102439239/160295710-2ce3b174-ec88-46d7-9cd3-6ae3b6644c7c.png">

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1007a.closed-alpha` version.
