### ISSUE TITLE
ships lost in the instances

### ISSUE THREAD

**Issue by AyartbeniYakub** [SuperGO2/supergo2-issues#180]
The h3s of the ships firing at us are falling from us.
Although 2 out of 500 ships are dropped, 498 are lost and 2 are coming back

**Comment by Tuni67** [comment]
I have the same issue. My ships were only damaged on the shield but after stopping the instance i lost all 300 ships... in the stack that was attacked

**Comment by ToxicSSJ** [comment]
Please follow the Issue format.
