### ISSUE TITLE
Selling commander card disappears from inventory but not listed in Tc

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#181]
I sold 1 4* Alicia in TC for 1g to a player.  Immediately Tried to sell a 3 Evi and it did not post. I refreshed and tried to sell it (was still there) again then it disappeared from my inventory and was not in TC. As well no mail indicating it was purchased by another player. Also not found by *searching*  In TC

Sell 1 cc then attempt to sell another , if it will not post then refresh and attempt to sell again, it will no longer be visible in inventory.

You should be able to sell multiple cc in TC

**Comment by ToxicSSJ** [comment]
Can't reproduce.

**Comment by ToxicSSJ** [comment]
Moved to #217.
