### ISSUE TITLE
Planetary Weapons on ship Hulls are Bugged and will wipe out your fleets if you try to delete them

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#182]
DANGER WILL ROBINSON!

Build a design with lander module 1. Attempt to fleet it or sell in TC .  It will not populate correctly. It will be listed As *0* ships in the create fleet menu. IF you attempt to delete it, it will delete the very first stack of ships in you fleet menu bar .

You should be able to build Ship hull with Pd weapons, They are very important in pve and pvp ( ill get to that next)
**Screenshots**
https://jmp.sh/c3mj5Sd

**Comment by StarfishPrime-1** [comment]
Iv'e done this twice now lol, despite knowing what would happen lol. Don't drink and fly folks!

**Comment by StarfishPrime-1** [comment]
#173 may be the same issue but I have not got a response

**Comment by AyartbeniYakub** [comment]
My ships bali and rocket

16 Tem 2022 Cmt 23:51 tarihinde Jay ***@***.***> şunu yazdı:

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307a.closed-alpha` version.
