### ISSUE TITLE
galaxy screen bug

### ISSUE THREAD

**Issue by KillAwesome** [SuperGO2/supergo2-issues#185]
when you go to the galaxy screen and try to scroll sometimes it bugs the game and doesnt allow you to click on the planet usually causing you to have to figure out the coordinates and refreshing then typing it in to click on the planet
(old server problem that is persisting here)

**Comment by irtusb** [comment]
that is a client bug present in original

**Comment by ToxicSSJ** [comment]
Original flash client bugs are not priority for us since we will build a new client in the future.
