### ISSUE TITLE
Ship merging does not work

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#19]
Unique Title: Ship merging does not work
Description: Trying to merge fleets in the space base does not update the fleet.
How to reproduce: Merge fleets in the spacebase.  Number of ships updates but not the fleets. On refresh and first look on that fleet shows no ships, second look it will reset to per merge attempt.  Modifying fleets works correctly

**Comment by ToxicSSJ** [comment]
This issue will be replaced by #110.
