### ISSUE TITLE
No puedes "robar" satelite de recursos Aliados

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#190]
**Describe the bug**
Solo vi que esto ocurre con los satelites de tier (especial) osea el mas grande
el satelite al terminar su tiempo de recoleccion (24hs) automaticamente aparece como que ya te han "robado" las 5 veces que se supone que pueden, pero ademas de mostrarte una reduccion de recursos visual 50%, te da la totalidad de ella el 100%
1. Go to 'Space staion'
2. Click on '.enter.'
3.  haz satelites de tier (especial)

**Expected behavior**
Amigos puedan robarte y tu obtengas una reduccion de los recursos recolectados

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307a.closed-alpha` version.
