### ISSUE TITLE
instance fleet bug

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#193]
**Describe the bug**
i made 7 fleets for instance 8 , 1 hitter and 6 fleets each 1 ship
atfer i8 done the 6 fleets were destroyed , but after i tried again when makeing fleets full he3 its showing the 7 fleets ( which 6 destroyed ) then i choosing fleets for instance its showing only one ,

**To Reproduce**

**Expected behavior**
the 6 fleets which destroyed shouldn't appear cuz i dont have it , i have only one 

**Screenshots**

![instance fleets](https://user-images.githubusercontent.com/108695969/179575313-30c3dde4-033f-48b9-b845-93fca838ce0f.png)

**Additional context**

**Comment by CUrvaSudMilano** [comment]
or let me call it i lost my fleets in instance 8 , that's would be better

**Comment by ToxicSSJ** [comment]
Moved to #192.
