### ISSUE TITLE
La sesion se cierra si no colocas nombre al planeta para inciar a jugar

### ISSUE THREAD

**Issue by FelipeVP04** [SuperGO2/supergo2-issues#194]
1. Al iniciar un nuevo planeta, eliges el bioma
2. Si no colocas un nombre a tu planeta 
3. La se sesion se cierra automaticamente y tienes que volver a inicar sesion 

Cada ves que quieras iniciar un nuevo planeta y no colocas el nombre se repite el proceso 
Una sugerencia es que pongan una alerta de colocar el nombre obligatorio sin que se cierre la sesion

**Comment by darlinxpro** [comment]
Esto se arregla poniéndole un required al input() nombre de planeta

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0510a.closed-alpha` version.
