### ISSUE TITLE
wordgame selects wrong winner

### ISSUE THREAD

**Issue by irtusb** [SuperGO2/supergo2-issues#195]
**Describe the bug**
if multiple players answer correctly the game, the last of them is chosen as the winner instead of the first

**To Reproduce**
. wait until wordgame starts
. multiple players write the answer before the winner is announced
. the winner is announced, but it will be the last one of the right answers

**Other info**
Example:
```
System: The word is: XXX
Alicia: XXX
Bob: XXX
System: Congratulations Bob!
```

**Comment by ToxicSSJ** [comment]
Removed with the word game.
