### ISSUE TITLE
Contraataque extremo

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#196]
**Describe the bug**
el contra ataque extremo no funciona adecuadamente

**To Reproduce**
1. Creas una nave con el plano "extreme counterattack lll"
2. Mandas las naves a instancia
4. El daño maximo es de 200.000 puntos cuando en realidad debe ser 600.000 en 3.000 naves ya que es 200x3000

**Expected behavior**
Debe ejecutar 600.000 de daño con el plano investigado al nivel 3 teniendo un slot de 3.000 naves

**Screenshots**
![qweqwe](https://user-images.githubusercontent.com/108841838/179989574-e74bd039-f968-4d03-b3bd-72e091811ca6.png)

**Additional context**
en cualquier instancia de la 1 a la 9 persiste este problema, se requiere urgente solucion

**Comment by skyprime17** [comment]
It does not deal 600.000 damage because only the effective ships reflect and not all 3000 ships.
(1024*200 = 204.800)

**Comment by Monchoplay** [comment]
sistema que pienso erroneo, pero va en suggest, no existe un bug, asi es el sistema actual
