### ISSUE TITLE
TARGET

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#197]
**Describe the bug**
Las naves en instancias toman mal a su objetivo

**To Reproduce**
Produce que las naves enemigas no tomen el objetivo que deben
1. Instancias
2. Instancia numero 9
4. En el turno numero 2 dejan de atacar al tanque aunque cumpla las condiciones de ser objetivo

**Expected behavior**

**Screenshots**
![22222222222222222222](https://user-images.githubusercontent.com/108841838/180037978-54380cc9-0480-429a-b7c6-4463db2ddffd.png)

**Additional context**
En el turno numero 1 si el tanque es el unico en el rango de las flotas enemigas, es atacado normalmente

**Comment by Colorap8** [comment]
los laser apuntan a max attack creo, no a max durability

**Comment by ToxicSSJ** [comment]
Moved to #198.
