### ISSUE TITLE
Resource production not updated correctly

### ISSUE THREAD

**Issue by irtusb** [SuperGO2/supergo2-issues#199]
**Describe the bug**
Resource production is not correctly updated after building a resource extractor. It does not trigger resource production side quests.

**To Reproduce**
. Build or upgrade a resource building
. Productivity is not updated
. Build or upgrade a second resource building
. Productivity will be updated but to the value it should be before the second upgrade
. Reload game
. Productivity will show correct value

**Expected behavior**
. Values should be updated correctly right after finishing a building or upgrade

**Screenshots**
![cap](https://user-images.githubusercontent.com/300455/180135410-6e00dd73-a876-44ee-9afa-ab59a61cfebc.PNG)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2207a.closed-alpha` version.
