### ISSUE TITLE
Recycling Plant not implemented

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#20]
Unique Title: Recycling Plant not implemented
Description: The Recycling Plant is not implemented
How to reproduce: Try to destroy ships in the Recycling Facility. I understand that it is not yet implemented but I could double my test speed if I had a way to remove old ships

**Comment by Truce-R** [comment]
check out this excel sheet when you get a moment, it is in the #battle-test discord channel under the pinned section. I attached a screenshot as well.

https://docs.google.com/spreadsheets/d/1oHuGxNNCG4QhLbI-3fzDxUx4V82NlcfaWEWNNLFVL58/edit#gid=
<img width="402" alt="Screen Shot 2022-03-27 at 3 10 58 PM" src="https://user-images.githubusercontent.com/85980370/160296894-61f3b757-0bdb-43cc-8cdc-89e58fb7ca5c.png">
0

**Comment by StarfishPrime-1** [comment]
I totally understand , Is there another way that I can delete these ships? can I have a second acct to sell them to?

**Comment by Truce-R** [comment]
You should be able to sell it to another account, the trade center is marked as completed but I have not tested it first hand yet.

**Comment by Truce-R** [comment]
I just tested the trade center to confirm and yes, it is working.

**Comment by ToxicSSJ** [comment]
Remember that this thing are not bugs and not need to be reported here, in any case you can ask for anything change into your account via discord chat. Anyway, this feature was added in the `V2022.35b.beta-dev` version.
