### ISSUE TITLE
Reflective plating not activate

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#201]
**Describe the bug**
i17 cerberus direcctional weapon have a reflactating plate and does not activate
this is the difficulty of the mission
https://user-images.githubusercontent.com/108563861/180315001-ce8d1923-04ac-4452-aaea-7d97606600e8.mp4

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2707a.closed-alpha` version.
