### ISSUE TITLE
Zephy have 100% attack twice instead the 100% critical hit

### ISSUE THREAD

**Issue by Zacmadness** [SuperGO2/supergo2-issues#202]
**Describe the bug**
Well, literally zephyrus attack twice 100% instead the critical hit xd

**To Reproduce**
1. Go to 'create any fleet with zephyrus'
2. Click on 'any instance'
3. Scroll down to 'just wait they attack'

**Expected behavior**

**Screenshots**
![Screenshot_2022-07-21-19-07-19-121_com cloudmosa puffinFree](https://user-images.githubusercontent.com/108496089/180331057-bc87793e-ded8-4098-93fd-d9bdf7480f32.jpg)

**Additional context**
Zephyrus op lmao

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2907a.closed-alpha` version.
