### ISSUE TITLE
You can't use bloodmary bp

### ISSUE THREAD

**Issue by Zacmadness** [SuperGO2/supergo2-issues#203]
**Describe the bug**
You can't use bloodmary bp, no matter how much click you do

**To Reproduce**
1. Go to 'inventory'
2. Click on 'use bloodmary bp'

**Expected behavior**
I wanted to create cybra with tier 5 weapon lol but now I can't xd

**Screenshots**

**Additional context**
Ballistic rules

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2207a.closed-alpha` version.
