### ISSUE TITLE
PERDIDA DE CARTAS DE INVENTARIO

### ISSUE THREAD

**Issue by IronMaiden-Mike** [SuperGO2/supergo2-issues#204]
**Describe the bug**
Estaba realizando una fusion de cartas de alicia, tenia 3 cartas 4* y 1 carta 3* al momento de realizar la fusion de cartas que por cierto fallé obviamente perdí las dos cartas 4* que se utilice, pero de mi inventario desaparecio mi otra carta 4* que me tuvo que haber quedado. El juego se me trabo despues de realizar la fusion hice refresh y cuando regrese ya no estaba en inventario

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2207a.closed-alpha` version.
