### ISSUE TITLE
mail box bug

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#205]
**Describe the bug**
if you delete msg contains unclaimed items it will be deleted as empty msg

**To Reproduce**

**Expected behavior**
if you have any item in the msg ,  you should get pop out msg warning you that you have unclaimed item 

**Screenshots**
no need 

**Additional context**

**Comment by Tuni67** [comment]
https://user-images.githubusercontent.com/108492773/180448925-946ddfcd-31be-445f-8df2-00db96d7f52f.mp4

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307a.closed-alpha` version.
