### ISSUE TITLE
Web Mall doesnt provide the correct amount of loudspeakers

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#206]
**Describe the bug**
If you buy 10 loudspeaker for 1 Voucher you only get 1 Loudspeaker.

**To Reproduce**
1. Go to Webmall
2. Go to page 2 on "All Items"
3. Buy Loudspeakers

**Expected behavior**
You should get 10 loudspeakers

**Video**

https://user-images.githubusercontent.com/108492773/180450280-ac86be5a-38a2-48b7-80bf-4c7de06c6abe.mp4

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2507a.closed-alpha` version.
