### ISSUE TITLE
Mision de comandantes

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#207]
**Describe the bug**
Mision Military rank dont work

**To Reproduce**
No se puede cobrar la mision
1. misiones
2. misiones, no aparece como concluida
4. deberia de poder cobrarse la mision de subir estrellas de un comandante

**Expected behavior**
Se espera el cobro de la mision

**Screenshots**
![qweqwe](https://user-images.githubusercontent.com/108841838/180493407-aa414325-6942-4d17-9296-18867f9b8203.png)

**Additional context**
No hay contexto adicional

**Comment by irtusb** [comment]
that mission is about using a 3* commander, not only having it in inventory

**Comment by spectuu** [comment]
Duplicated #222
