### ISSUE TITLE
Dismiss all common commanders destroy gems that were equipped

### ISSUE THREAD

**Issue by Kariuzz** [SuperGO2/supergo2-issues#208]
**Describe the bug**
In the original Go2 if common comander was equipped a gem, the commander wasn't errased

**To Reproduce**
1. Go to 'Commander'
2. Click on 'Dismiss all common comanders'

**Expected behavior**
The common commanders that have gems equiped, should not be destroy,

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0808a.closed-alpha` version.
