### ISSUE TITLE
Damage modifiers

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#21]
Unique Title: Damage modifiers
Description: Damage modifiers are a bit whack.
How to reproduce: observe front, mid ,rear attacker damage . side , rear attacker damage. hull type vs damage type. I assume not fully implemented. for example in I1 the pirates in the second row appear to be doing double damage as the front row. (use a small non weaponized stack)

**Comment by ToxicSSJ** [comment]
This issue was fixed in the latest updates.
