### ISSUE TITLE
Missing ships when trying to sell on the market

### ISSUE THREAD

**Issue by Kamikazexp** [SuperGO2/supergo2-issues#211]
when trying to sell ships on the market it doesn't work and its value changes to 0

1. Go to Auction house
2. Click on Sell
3. select the number of ships, the price and sell

![image](https://user-images.githubusercontent.com/109710388/180580246-f68ca6ee-907e-40bb-a536-f042ecf056d2.png)
![image](https://user-images.githubusercontent.com/109710388/180580266-dea79015-506c-4d28-9827-2055ce1acf29.png)
![image](https://user-images.githubusercontent.com/109710388/180580278-0d9dda30-d504-4bbc-bff3-ec8c0bc6b125.png)

**Comment by StarfishPrime-1** [comment]
@toxic, can you check #182 as well? , I believe its related

**Comment by StarfishPrime-1** [comment]
possibly #173 as well

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307a.closed-alpha` version.
