### ISSUE TITLE
The mail systems doesn't works very well

### ISSUE THREAD

**Issue by Kariuzz** [SuperGO2/supergo2-issues#213]
**Describe the bug**
Sometimes, when you recive a new mail, appears the new mail icon, but when you click in it the new mail there isn't nothing, loosing the reward of this new mail
![Sin título](https://user-images.githubusercontent.com/109613356/180615951-42ceafdd-8faf-4ec4-af91-560a9cfd96ff.png)

**Comment by irtusb** [comment]
what kind of email were you expecting? a player message, auction update, instance reward, ...?

**Comment by Colorap8** [comment]
auction update in this case

**Comment by ToxicSSJ** [comment]
Moved to #217.
