### ISSUE TITLE
Generating Chips freezes the game

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#214]
**Describe the bug**
Trying to generate a chip freezes the game/

**To Reproduce**
1. Go to Generate Bionic Chip
2. Click on 1 or 2
3. See error

**Expected behavior**
A chip should be generated

**Screenshots**

https://user-images.githubusercontent.com/108492773/180621157-3b135a6a-62dc-4e90-815c-f7f495b21c3b.mp4

**Additional Info**
I also tried to convert a commander into CG and the Comm disappeared and I didn´t get CG. Issue was fixed after restarting. Comm remained and no additional CG was added. Keep an eye out regarding that issue. Could be something deeper or a glitch client side.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2707a.closed-alpha` version.
