### ISSUE TITLE
Detailed: Fleets in Instances are not moving

### ISSUE THREAD

**Issue by zRulerr** [SuperGO2/supergo2-issues#216]
# **Fleets in Instances are not moving**
This is a tough one to exactly pin down. The Game Freezes under some certain circumstances while doing instances.

## **1. To Reproduce**
Like I said above, I can't exactly pin down when the Problem occurs all the time but I can give you some examples.

   ### **1.1 Example 1**
   I have 6 Fleets. 5 Attack Fleets and 1 Tank Fleet doing **Instance 9**. Here, **IF** my tank place is at the last ,,Position" (Position 6),
   the Instance will **not** start. I can do everything else (Haven't noticed anything weird besides the instance bug). My Fleets as the 
   enemy fleets will not move nor attack.

![image](https://user-images.githubusercontent.com/108607807/180622696-7b127f17-a679-4359-89e6-0ce09da894d9.png)
![image](https://user-images.githubusercontent.com/108607807/180622794-b02d6249-50c7-4b94-a66d-c1c8e5b59d52.png)

Fleet's are stuck

   **but**
   
   **IF** I change the ,,Order" of my Fleets f.e I pick my tank fleet first, the instance will just go as usual. I checked it with multiple 
    orders but it only happens when my Tank fleet is picked last.

![image](https://user-images.githubusercontent.com/108607807/180622781-14f39b56-716f-4b31-bd64-a1eaaccc3efd.png)
Fleet's not stuck

   ### **1.2 Example 2**
   **IF** I made another ,,Tank Fleet" with 1800 Ships at 1 Stack. Now, I pick my Fleets as usual in any Order and the Instances works 
    again.
    
![image](https://user-images.githubusercontent.com/108607807/180622831-e818d703-13f3-4870-9136-0b66871f6f4a.png)
Fleets not stuck
    
   **HOWEVER**
    
**IF** I increase the stack size to 1900 Ships (100 more) the same bug occurs again.

![image](https://user-images.githubusercontent.com/108607807/180622848-edee17b1-ae22-4165-a0ea-85d404739638.png)
Fleet's stuck again

### **What I already tried**

- Restarting game
- Waiting long enough to see if the fight is actually ,,calculated"
- Remade the Fleets (but with same ships)
- Change commander of the bugging Fleet

### **When did this Bug first occur ?**
- After Version **[V2022.2307a.closed-alpha]**

### **Additional Notes**
- My Fleets were in i9 while the Server was restarting, but the Instance was completed after the server  was up again.

<sub> So u see why I can't pin down all the different circumstances where this bug can occur, but maybe this will help.</sub>

**Comment by Tuni67** [comment]
Additionally: After this problem occurred the server started to lag quite heavily sometimes. No idea why tho.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307b.closed-alpha` version.
