### ISSUE TITLE
Can reset a commander's level / attributes while it is fleeted

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#22]
Unique Title: Can reset commander attributes while it is fleeted
Description: Can reset commanders when fleeted
How to reproduce:  Fleet a commander and reset its level. It will not let you turn into a card (says it has gems) which it does not but that seems minor

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.606b.beta-dev` version.
