### ISSUE TITLE
Cant use a SP Card

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#223]
**Describe the bug**
You cant use SP Card

**To Reproduce**
1. Buy a SP Card
2. Try to use SP Card
3. See error

**Expected behavior**
You gain 10 SP

**Additional context**
Wanted to steal resources :C

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2507a.closed-alpha` version.
