### ISSUE TITLE
commander bug

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#224]
**Describe el bug**
when i click on commander list i see some of my commanders status in battle but they are actually NOT

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. click on military's icon 
2. click on commander 
3. click on commander and see status in battle
3. he is not in battle 

**Comportamiento esperado**
Al cerrar el catalogo no debería salir ningún error.

**Imágenes**

![commander bug](https://user-images.githubusercontent.com/108695969/180702608-bc06fb41-8291-4e3c-ae35-6e8350018ecc.png)

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2907a.closed-alpha` version.
