### ISSUE TITLE
Scrapping all chips delete a useful ship and doesn't delete a useless one

### ISSUE THREAD

**Issue by ABanC1001** [SuperGO2/supergo2-issues#226]
**Describe the bug**
Scrapping all chips delete a useful ship and doesn't delete a useless one

**To Reproduce**
1. Go to generate bionic chip
2. Click on generate chip (A lot of times the 1 or 2 option)
3. Then when your "Chip inventory" is full scrap all

**Expected behavior**
The only chips that should be deleted are those that are named scrap chips, no the others.

**Screenshots**
![image](https://user-images.githubusercontent.com/108493836/180751341-0e327ca6-e54c-4b33-974d-c2ebacba7621.png)
![image](https://user-images.githubusercontent.com/108493836/180751360-c13e42c2-b4c1-4390-a5e2-5254d68d5685.png)
![image](https://user-images.githubusercontent.com/108493836/180751462-7c66cb42-7f8f-4bbc-8cf6-20e0352a8bb3.png)

**Additional context**
N/A

**Comment by ABanC1001** [comment]
I think it can be seen in the images, the structure chip was deleted instead of a scrap chip.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1008a.closed-alpha` version.
