### ISSUE TITLE
Error - Construir naves

### ISSUE THREAD

**Issue by darlinxpro** [SuperGO2/supergo2-issues#227]
cuando realizo el click a las naves que deseo contruir, claramente sabiendo la cantidad que puedo contruir, se ponen a contruir pero graficamente no me las muestra hasta que cierro y vuelvo a abrir la fabrica de naves.

esto muestra ejemplo contruir 25 naves en el slot 5, no me muestra pero en si se estan construyendo.
![bug](https://user-images.githubusercontent.com/88944300/180890501-fe8d399d-c875-4e46-a16e-ab9c02c495cd.png)

aqui muestro despues de cerrar y abrir la fabrica

![bug](https://user-images.githubusercontent.com/88944300/180890586-a1fdadcf-2d26-4815-a47b-88c46391ec8f.png)

Ayer estaba todo bien, todo empezo a suceder desde que entre hoy, tambien puedo agregar que estoy utilizando el cliente del juego.

**Comment by irtusb** [comment]
related or duplicate of #210

**Comment by ToxicSSJ** [comment]
Please follow the right format.
