### ISSUE TITLE
Cannot type in fullscreen mode (original game issue)

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#23]
Unique Title: Cannot type in fullscreen mode
Description: I Cannot type in fullscreen mode
How to reproduce:  Full screen and attempt to enter text in any field. This was the same in the original and I was told it was asecurity thing but not convinced lol

**Comment by ToxicSSJ** [comment]
This is a flash limitation: [Check here](https://community.adobe.com/t5/animate-discussions/flash-bug-can-t-type-in-textarea-in-fullscreen-mode/m-p/796089)
