### ISSUE TITLE
ships disapear(visual problem)

### ISSUE THREAD

**Issue by KillAwesome** [SuperGO2/supergo2-issues#231]
**Describe the bug**
when you build a fleet and then refresh if you click on the fleet most of the ships do not spawn in and actually dont show on the bottom panel. (quick side note tested before posting just now it seems to work better with 2 different ships
**To Reproduce**
1. Go to '...' create a fleet and put 2-5 stacks of ships i find 2 different ships works better to see this bug
2. Click on '....' save fleet and then leave game, rejoin click on the fleet itself 
4. See error youll see either all but one stack is gone or just 1 stack is gone. (note this works better with 2 different styles of ships harder to reproduce with just 1 of the same ship)

**Expected behavior**
expectation is to see the ships in the fleet (doesnt actually hurt anyone just weird)

**Screenshots**

![ships gone 1](https://user-images.githubusercontent.com/109487703/181148780-7ad9d047-bebd-4ee7-8f02-3f7553767407.PNG)
![ships gone 1 5](https://user-images.githubusercontent.com/109487703/181148797-816abee6-e1d7-4b71-9de2-f7de1b27859c.PNG)
![ships gone 1 8](https://user-images.githubusercontent.com/109487703/181148810-a491eae2-198d-4da3-9963-817a1b632c39.PNG)
![ships gone 2 0](https://user-images.githubusercontent.com/109487703/181148820-49777a88-020a-4e84-94f8-1f85c84e8ef3.PNG)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
