### ISSUE TITLE
FOR CHİPS

### ISSUE THREAD

**Issue by AyartbeniYakub** [SuperGO2/supergo2-issues#232]
locked chips disappear when combined
![1](https://user-images.githubusercontent.com/109309041/181290590-6d9bdda9-5360-4baa-b3f2-b6a27dcba2dc.png)
![2](https://user-images.githubusercontent.com/109309041/181290622-a3016bdf-6a75-4854-a47e-74315682af7b.png)

**Comment by ToxicSSJ** [comment]
Please use the right issues format.
