### ISSUE TITLE
Bug arena

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#233]
**Describe el bug**
Los comandantes mueren

**Como reproducirlo**
Crear naves, entrar en arena y luchar
1. abrir arena
2. crear arena con flotas
3. iniciar batalla
3. si el comandante muere en arena, lo considera muerto el juego entonces debes usar tarjeta

**Comportamiento esperado**
No debe de pedir revivir al comandante al terminar la arena, muera o no

**Imágenes**
.

**Información Adicional**
.

**Comment by ToxicSSJ** [comment]
Can't reproduce it.

**Comment by ToxicSSJ** [comment]
Closed because it could never be reproduced.
