### ISSUE TITLE
bug de mercado

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#235]
**Describe el bug**
No se ven los item en mercado, desaparecen

**Como reproducirlo**
click en "aution"
1. Abrir el catalogo
2. ir a la pestaña "selling" y cambiar a sell o purchase
3. .
3. desaparecen los items

**Comportamiento esperado**
que aparezcan los item y las paginas

**Imágenes**
![qqqq](https://user-images.githubusercontent.com/108841838/181360986-d9228e29-c816-4de7-8e2e-cccc3383be48.png)

**Información Adicional**
no hay

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2907a.closed-alpha` version.
