### ISSUE TITLE
Sofia wrong bonus

### ISSUE THREAD

**Issue by ABanC1001** [SuperGO2/supergo2-issues#236]
**Describe the bug**
When Sofia triggers her ability she get more than 3 movements.

**To Reproduce**
1. Go to create fleet, create a fleet with Sofia as commander.
2. Click on instances
3. Start any instance and retry until Sofia triggers

**Expected behavior**
Sofia should only get 3 movement points when she triggers

**Screenshots**
Im really sorry for the quality of the video, but it can be replicated also without that visual bug (It was in instance 1), to add more context this was the fleet:
![image](https://user-images.githubusercontent.com/108493836/181405379-679aee01-f1e6-4dd1-8f38-182087636799.png)

**Additional context**
This was texted in instance 1, with only 1 fleet with sofia 6* lvl6, purple negator VI and blue aegis III

https://user-images.githubusercontent.com/108493836/181405286-5838a9b5-a218-4ad9-855d-4e963a028d40.mp4

**Comment by ABanC1001** [comment]
https://user-images.githubusercontent.com/108493836/181406197-6f7a0575-7180-4b37-91b5-d215c7e186c1.mp4

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2907a.closed-alpha` version.
