### ISSUE TITLE
EXtreme counter attack

### ISSUE THREAD

**Issue by AyartbeniYakub** [SuperGO2/supergo2-issues#237]
**Describe the bug**

**To Reproduce**
1. extreme counter attack consumes a lot of he3
3. please minimize consumption
![Adsız1](https://user-images.githubusercontent.com/109309041/181407220-a3046e61-3061-4058-b00f-7d356078d533.png)
![Adsız2](https://user-images.githubusercontent.com/109309041/181407228-1889ebb7-00fd-4ace-b26b-13fa5b6156fa.png)

**Comment by ToxicSSJ** [comment]
This is not a bug. Please make the calculations and describe the expected behaviour.
