### ISSUE TITLE
Ecesivo gasto de he3 en modulos de ataque

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#238]
**Describe el bug**
Se esta gastando mucho he3 en los modulos de ataque

**Como reproducirlo**
1. crear flotas
2. llenarlas de he3
3. enviarlas a una instancia
3. el gasto de modulos de ataque es excesivo

**Comportamiento esperado**
Se debe consumir menos he3 por ataque

**Imágenes**
.

**Información Adicional**
,

**Comment by Gust0Angel** [comment]
creo que es porque falta  poner mas tech de las armas a mi me pasa lo mismo

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0510a.closed-alpha` version.
