### ISSUE TITLE
Private Messages 

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#239]
**Describe the bug**
Private Messages are quite bugged, if you write some characters the sentence disappears. If you press enter the game send dozen of empty messages. 

**To Reproduce**
1. PM someone
2a. click ENTER( empty sentences should appear)
2b. write something that contains : 
3. See error

**Expected behavior**
PMs should work properly, 

**Screenshots**
![uffff3](https://user-images.githubusercontent.com/108492773/181609706-93e507d2-4883-4331-896c-96b4a5ad9ec4.JPG)

**Additional context**
Did not test all characters that could make the sentences disappear, most likely its  :   ,other symbols were not tested. If someone finds any comment it down below.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2008a.closed-alpha` version.
