### ISSUE TITLE
Negative Level Percent

### ISSUE THREAD

**Issue by DevTruce** [SuperGO2/supergo2-issues#24]
Description: I got to the 95% area and then once the next building was upgraded (he3 extractor) I got -3% experience bar at level 101 going to 102. 

How to reproduce: gain enough experience to go from level 101 to 102   

Expected behavior: you should be able to level up to the next level 

<img width="1440" alt="-3" src="https://user-images.githubusercontent.com/85980370/160298723-060c51f0-f3cb-4ced-a39e-b04c4ffb6ef0.png">
<img width="1440" alt="-3-2" src="https://user-images.githubusercontent.com/85980370/160298726-1cf4dcf7-4863-4e21-b40f-8db8b7214fbe.png">
<img width="1440" alt="-3-3" src="https://user-images.githubusercontent.com/85980370/160298729-1a39da00-a07f-4614-8ab5-4647b6865c15.png">
<img width="1440" alt="-3-4" src="https://user-images.githubusercontent.com/85980370/160298843-7276fb75-4c72-4b45-a25a-43636df1678f.png">

**Comment by spectuu** [comment]
I can't reproduce this @Truce-R
