### ISSUE TITLE
Bug visual de naves

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#241]
**Describe el bug**
Explicacion en el video

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. .
2. .
3. .
3. .

**Comportamiento esperado**
.

**Imágenes**
https://drive.google.com/file/d/1ai_Wuvgi_woSf_difctTTWfp3SU31QcH/view?usp=sharing

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by darlinxpro** [comment]
Me pasa lo mismo al crear flotas
