### ISSUE TITLE
black market bug 

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#242]
**Describe the bug**

**To Reproduce**

**Expected behavior**
i tried to convert all metal to he3 but i couldn't , then i minus 1 metal , then it works 
**Screenshots**
https://youtu.be/5Wb_J_pw5hs

**Additional context**

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0808a.closed-alpha` version.
