### ISSUE TITLE
bug de he3 mal calculado

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#243]
**Describe el bug**
explicacion en el video

**Como reproducirlo**
.
1. .
2. .
3. .
3. .

**Comportamiento esperado**
.

**Imágenes**
.https://drive.google.com/file/d/1m8dP9G183LkHyjk29FT0y0ocfSL7jIvl/view?usp=sharing.

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0510a.closed-alpha` version.
