### ISSUE TITLE
The scatter reaches 100% or higher by the research Exaltation

### ISSUE THREAD

**Issue by Kariuzz** [SuperGO2/supergo2-issues#247]
**Describe the bug**
This research must to upgrade de damage of scatter at 80% when the fleet enemy have a lower structure, but causes that your fleet attack reaches to 100% of scatter or higher.
**To Reproduce**
1. Go to 'Research "Exaltation" and after check it'
2. See their damages and the scatter that causes in a fleet enemy when you have more structure

**Expected behavior**
The research only must upgrade the damage of the scatter and it musn't overpass the 100%

"Video of the facts"

https://user-images.githubusercontent.com/109613356/182725004-386cb590-d2f2-4a67-b542-121473b22510.mp4
If you needs a better quality video tell me for discord because github don't allows me submit a video very higher
Check for damages that the tiamat's have received 
![Sin título](https://user-images.githubusercontent.com/109613356/182726302-db77521b-1530-49a1-b4be-33c0093d7dff.png)

**Additional context**
This happen because this research upgrades the scatter rate and not upgrades the scatter damage
Multidirectional Assault: 30% of scatter rate
Sharpnel Research : 4% of scatter rate
Exaltation : 80 % scatter damage but in this case upgrades the rate

The real scatter with this three upgrades must be 61.2

**Comment by Tuni67** [comment]
kariuuz you can compress a video with clideo, it allows you to downsize a 70mb video to 7mb

**Comment by Tuni67** [comment]
Also, Tiamat use Chrome armor and receive 150% explosive dmg while Whirlpool use Regen that only receives 100% of the explosive dmg.

**Comment by Kariuzz** [comment]
Check the issue, this is not the case, because the damage of scatter ignores the defensive modules.
The sum of all upgrades gives 114% the scatter and are bad.
the sum of all upgrades will be: 34% of scatter rate + 80% of scatter damage: it's results in 61,2% of scatter and not 114%
80% + 34% = 114% 
if tiamats recives 150% of damage their will be destroyed for a bestial damage

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0308a.closed-alpha` version.
