### ISSUE TITLE
Comandantes junto con naves se buguearon al instante cuando cree el spacedock.

### ISSUE THREAD

**Issue by calacavenezolana** [SuperGO2/supergo2-issues#248]
**Describe el bug**
Una descripción clara y concisa de que hace el bug.
No es posible que sea claro pero es un 50% seguro que se efectuo luego de haber colocado el spacedock mientras hacia instancia

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. tener naves en instancia
2. colocar spacedock
3. al terminar el spacedock cuando entras a ver tu instancia, no veras ninguna nave
4. reinicias el juego y tus comandantes y naves estan armadas pero no estan por ningun sitio

**Comportamiento esperado**
Al cerrar el catalogo no debería salir ningún error.

**Imágenes**
Aquí agregaré enlaces a imagenes/video o también puedo arrastrar el contenido.
![3](https://user-images.githubusercontent.com/108645818/182939535-45b8616d-3a86-495d-924c-fad444cebd1e.PNG)
![2](https://user-images.githubusercontent.com/108645818/182939539-e52a8a47-b4cd-49a4-874b-283bec10e288.PNG)
![1](https://user-images.githubusercontent.com/108645818/182939541-9bcd20ca-d761-4bc2-8d77-3080f226fc3a.PNG)

**Información Adicional**
Aquí debo agregar información adicional del bug.
nada que agregar

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2110a.closed-alpha` version.
