### ISSUE TITLE
alliance store lost items

### ISSUE THREAD

**Issue by darlinxpro** [SuperGO2/supergo2-issues#252]
**Describe el bug**
I left the alliance that is Apha Legends, to enter the confederation, 2 hours have passed and the items have not arrived by mail as appropriate.

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Join alliance Building
2. Click to Left Alliance
3. the items saved in alliance store are missing

![bug](https://user-images.githubusercontent.com/88944300/183150789-3975a652-211a-4fb9-a130-a81f23e613d3.png)

**Comportamiento esperado**
when I click leave alliance, send me everything that was saved in the inventory of the alliance by correspondence

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
