### ISSUE TITLE
Weapon bionic chips not working.

### ISSUE THREAD

**Issue by 0Nimroth** [SuperGO2/supergo2-issues#254]
**Describe the bug**
Currently it appears you get no difference in damage with or without weapon chips applied to commanders

**To Reproduce**
1. Form a fleet using ships with 1x rocket frame and at least 2 movement, in stacks of 3 ships in the front row, using closest target and a common commander with below 10 speed, and on an account without missile science done.
2. Send the fleet into instance 1 and let the front row fire once, take note of the damage values and exit the instance.
3. Repeat several times without chips, several times with a min missile chip and ideally a greater number of times with a max missile chip.
4. Compare the difference.

**Expected behavior**
What you would expect is for the min weapon chip to reduce or eliminate the variance between the min and max hits so that each hit in this particular scenario would be the exact same value except for crits/double hits.
Similarly you would expect the max weapon chip to significantly increase the highest variance you get as well as raise the overall average between all of the combined hits.

**Screenshots**
![Go2 chip test samples](https://user-images.githubusercontent.com/110821539/183419048-13707c44-ef81-4e55-9e2c-77bc9c4dcccc.jpg)

**Additional context**
So far I've tested this using missile and directional chips, have yet to try with ballistic or ship based.

**Comment by StarfishPrime-1** [comment]
not implemented I think, also shhhhh

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2008a.closed-alpha` version.
