### ISSUE TITLE
Corps Player Limit

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#256]
**Describe the bug**
more players are in corp then the limit allows 

**Expected behavior**
working limit

![1](https://user-images.githubusercontent.com/101828275/183491022-6ad7245d-8c4e-4b11-a5a0-1b8dda719b7d.PNG)
![2](https://user-images.githubusercontent.com/101828275/183491040-cbf7bba9-eb84-4757-8ff0-e02e0d799467.PNG)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1008a.closed-alpha` version.
