### ISSUE TITLE
auction house visual bug

### ISSUE THREAD

**Issue by KillAwesome** [SuperGO2/supergo2-issues#257]
**Describe the bug**
when you put a ship in the auction house and try to search for it, it will not show up unless you go to the all tabs and look manually.

**To Reproduce**
1. Go to '...' auction house and post a ship
2. Click on '....' click on search for the ships 
4. See error you will not see the ship in the auction house until you go to the ships/all tab and scroll through the pages

**Expected behavior**
you are supposed to just type the ship and see all available ships in the auction house

**Screenshots**

![no ah history](https://user-images.githubusercontent.com/109487703/183569381-ab02f53a-9f79-44f5-87b4-daa1f9f3f7a6.PNG)
![no ah history 2 0](https://user-images.githubusercontent.com/109487703/183569395-439693a4-a77f-4bc7-9e30-bb8c8cb6cfc8.PNG)

**Comment by KillAwesome** [comment]
the ship from warner is the second picture to show what we are talking about

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2010a.closed-alpha` version.
