### ISSUE TITLE
missile research bug

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#258]
**Describe the bug**
missile research bug showing unknown time even its finsihed

**To Reproduce**

**Expected behavior**

**Screenshots**

![Missile bug](https://user-images.githubusercontent.com/108695969/183637191-e8eb7549-36ed-4733-bb65-4c5e1fb99a27.png)

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2110a.closed-alpha` version.
