### ISSUE TITLE
Corps Member Online Status

### ISSUE THREAD

**Issue by Truce-R** [SuperGO2/supergo2-issues#26]
Description: Corps members are always displayed as online, regardless of their actual status.

How to reproduce: have a friend go offline and check their status in your friend list to get their correct status, then reference their status within the corps member view. Alternatively, display the current online member status and compare.  

Expected behavior: corps member view should display an accurate player status.

<img width="396" alt="online-1" src="https://user-images.githubusercontent.com/85980370/160299397-8ede5539-ca1f-4dca-8edb-119cc2e61a02.png">
<img width="1440" alt="online-2" src="https://user-images.githubusercontent.com/85980370/160299398-f806a12a-2a91-4ad7-bab4-c87a2b197f9f.png">
<img width="1440" alt="online-3" src="https://user-images.githubusercontent.com/85980370/160299401-806c8bb0-8c7f-4767-90c7-4b58f71049ef.png">

**Comment by spectuu** [comment]
ready!
