### ISSUE TITLE
Planet defences taking 0 damage against lvl1 pirates.

### ISSUE THREAD

**Issue by 0Nimroth** [SuperGO2/supergo2-issues#262]
**Describe the bug**
Lvl1 pirate fleets using ship-based weapons deal no damage against lvl5-6 anti air craft guns as well as lvl3 thors, while the other weapons do damage.

**To Reproduce**
1. Start lvl1 pirates on a planet with lvl5-6 anti-air cannons and/or lvl3 thors.
2. Watch the ship-based fleets hit the anti-air cannons or thors

**Expected behavior**
You would expect the fleets to at least do a little damage rather than a flat 0 and for the sb to do more damage than the other weapon types.

**Screenshots**
![pirates](https://user-images.githubusercontent.com/110821539/184176081-f422d2d0-413d-4de9-8568-36a2c74183a1.jpg)

**Additional context**
Not sure if the problem is the same against meteors or particle cannons, or against pd at other levels.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2608a.closed-alpha` version.
