### ISSUE TITLE
Autogenerate by spam

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#264]
**Describe the bug**
If you click the "Auto generate" in CG screen very fast, you can observe some of your green chips getting deleted

**To Reproduce**
1. Go to 'CG Generation'
2. Click on 'Use a autoclicker on the "Auto generate button"'
3. Watch as some of the chips what are not supposed to be deleted get autodeleted

**Expected behavior**
Only scrap chips are supposed to be autodeleted

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
