### ISSUE TITLE
Ship Building Boost inv

### ISSUE THREAD

**Issue by Gabrielelelele** [SuperGO2/supergo2-issues#267]
**Describe el bug**
La investigación "Ship Building Boost" que aumenta un 15% la velocidad de creación de naves no se aplica.

**Como reproducirlo**
-Comprobar el tiempo de construcción una nave
-Subir la investigación
-El tiempo no varía en nada

**Comportamiento esperado**
Reducción de tiempo

**Información Adicional**
Según la wiki el tiempo de construcción de un Cybra 3 son 15 seg, en el diseñador de naves dentro del juego agregandole 1 escudo orbital el tiempo sube a 16 seg, al guardar el diseño y verlo en el <ship factory> tardaría 13 seg. (Solo se aplica el -19% del ship factory lvl 15)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2608a.closed-alpha` version.
