### ISSUE TITLE
Mercado bug

### ISSUE THREAD

**Issue by Alegher** [SuperGO2/supergo2-issues#270]
**Describe el bug**
cuando compras un item del mercado con cantidad 0 , el oro se te descuenta y el item no te llega

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Abrir inventario
2. seleccionar un item para colocar a la venta
3. poner en cantidad 0 y el  precio el que desees
4. poner a la venta
![bug mercado](https://user-images.githubusercontent.com/111233923/184540474-d94dd7c0-5ea3-40f6-b239-571c6fe51d7f.jpg)

**Comportamiento esperado**
no se podria poner a la venta el item

**Imágenes**

**Información Adicional**
Aquí debo agregar información adicional del [bug.]

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1408a.closed-alpha` version.
