### ISSUE TITLE
SS taking incorrect dmg

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#273]
**Describe the bug**
wrong dmg taken to the ss,   9 stacks = 9 dmg 

**To Reproduce**
send bali fleets "9 stack" to enemy base, watch them hit the ss
**Expected behavior**
the SS to take 9 dmg

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2008a.closed-alpha` version.
