### ISSUE TITLE
Visual Bug Cant see new planet ports happening,

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#277]
**Describe the bug**
Cant see new planet ports happening,
**To Reproduce**
have someone port next to you, notice you cant see them there

**Expected behavior**
to see it when it happens, 
**Screenshots**

**Additional context**
the only reason im adding this one is because in a fighting sense this is a nightmare, if i cant see my enemy port next to me, then i have no idea they are there if they dont send at me right away, 10 players could port next to me, send together and id never have seen them coming

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2608a.closed-alpha` version.
