### ISSUE TITLE
wrong name on fleeting radar menu

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#278]
**Describe the bug**
my names posted where the targets name should be posted 
**To Reproduce**
send to attack anywhere
**Expected behavior**
targets name to be on my destintion not my own planet 

**Screenshots**
![3](https://user-images.githubusercontent.com/101828275/184556704-f6cd1668-31b4-4ff9-aef4-c4dc4311a880.PNG)

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
