### ISSUE TITLE
Saved Fleet Formation

### ISSUE THREAD

**Issue by DevTruce** [SuperGO2/supergo2-issues#28]
Description: when you create fleet formations and save them they work but once you refresh the game they disappear

How to reproduce: create and save a fleet formation, refresh the game and check to see if the save fleet formations are still there

Expected behavior: your fleet formations should stay and only be deleted if you remove them or overwrite them

Video 1: https://jmp.sh/8krve0I

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.606b.beta-dev` version.
