### ISSUE TITLE
Corps chat remined working after leaving a corps

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#281]
**Describe the bug**
Corps chat remined working after leaving a corps
**To Reproduce**
be in corp, leave, notice green chat still working 
**Expected behavior**
no green chat
**Screenshots**

**Additional context**
green chat remained untill player joined another corps

**Comment by spectuu** [comment]
Done

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2110a.closed-alpha` version.
