### ISSUE TITLE
error with nick proc

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#282]
**Describe the bug**
ships def mod "qra" activated even tho nick skill activated 

**To Reproduce**
equip ships with qra, on nick commander, have them shot at and watch

**Expected behavior**
nicks skill to negate all reason for a def mod to engage

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2008a.closed-alpha` version.
