### ISSUE TITLE
Instancia final

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#288]
Las flotas en instancias se pierden antes de que se complete la animación de *batalla*.

Inicie una instancia. haz clic en *finalizar instancia* cuando recibas daño.

No debes perder barcos si se cierran antes de que termine la animación.

https://jmp.sh/esPsUSb

**Comment by StarfishPrime-1** [comment]
Je nes as parle les espanol , but I am learing!

**Comment by ToxicSSJ** [comment]
Please use the right format.
