### ISSUE TITLE
Pirate fleet  "displayed numbers" odd after taking damage

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#29]
Unique Title: Pirate fleet numbers displayed are changing in " **Battle movement phase**" AND " **Battle firing phase**"
Description: Pirate fleet numbers change 
How to reproduce: Its a negative damage thing maybe??  I used this design but likely easy to reproduce. 
http://krtools.deajae.co.uk/des/?d=31:370:1:240:1:265:1:426:1:469:1:90:1:92:1:91:1

111 ships on a center stack.  "**Battle movement phase #** "is always 065xxx. a 065500 equals 22 ships in the back row of the pirate fleet in the "**Battle firing phase**" . 065499 is a 21. 
I will send a vid once I figure out jumpshare login lol. <

^Strike
V2022.0307a.  This is still an issue.
Pirates def from *stacked* Ship-Based or  *Stacked* Missile with a very low *Ap* will sometimes cause the defending stack to stay *visible* but the ship counter for that stack is below 0 and disappears.

**Comment by StarfishPrime-1** [comment]
https://jmp.sh/Ng55skD

**Comment by StarfishPrime-1** [comment]
<img width="691" alt="Def default fire" src="https://user-images.githubusercontent.com/102439239/177226484-e36a17c8-237c-4b3e-aa19-f3a0ba346fe1.png">

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0407a.closed-alpha` version.
