### ISSUE TITLE
PERDIDA DE FLOTAS AL DEFENDER

### ISSUE THREAD

**Issue by darlinxpro** [SuperGO2/supergo2-issues#292]
**Describe el bug**
Pierdes todas las flotas al defender un planeta en este caso no era de la misma alianza, la batalla terminó antes de que las flotas llegaran, sin embargo se quedaron en el planeta, tuve que realizar un recall back osea devolverlas a mi planeta, al  llegar todos los comandantes estaban muerto y las naves desaparecidas, tampoco sali en el reporte de batalla, osea las naves nunca llegaron ni estuvieron en batalla.

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Defender un planeta no de la misma alianza
2. La batalla termina antes de que llegen tus flotas al planeta en defender
3. tus flotas permanecen en el planeta en defensa, aunque no se muestran en la estacion de ese planeta
3. haces devolver tus flotas en planeta defensa desde el gestor de transmision
4. tus flotas y comandantes llegan muertos

**Comportamiento esperado**
al finalizar la batalla antes de llegar las flotas tienen que devolverse automaticamente si ese planeta no es de la misma alianza. Y si es de la misma alianza deben permanecer alli hasta que el dueño de las naves las revuelva.

**Imágenes**
![error](https://user-images.githubusercontent.com/88944300/184733862-12a5bbf2-45da-4d1b-8b6e-c348dd916cd9.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2008a.closed-alpha` version.
