### ISSUE TITLE
Visual Bug in Ship Design

### ISSUE THREAD

**Issue by Gemini-GO2** [SuperGO2/supergo2-issues#294]
**Describe the bug**
You cannot view the entire description of the bottom module on the screen when that description is long, the visible length varies for different modules

**To Reproduce**
1. Go to 'Ship Designer'
2. Click on 'Defensive Module'
3. Scroll down to 'Gravity Maint. Facility-1' as an example the error occurs for multiple items
4. Hover over menu is only partial as it descends past bottom of visible window

**Expected behavior**
The whole box should be visible.

![graphic bug](https://user-images.githubusercontent.com/111343699/184827588-51d12782-b9c4-4b9e-a8d8-e5fcca8bcaee.jpg)

![image](https://user-images.githubusercontent.com/111343699/184828136-187c030d-bb60-41ac-a2db-fbbc77718c12.png)

**Comment by ToxicSSJ** [comment]
This is a client bug.
