### ISSUE TITLE
Rebote sin modulos

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#295]
**Describe el bug**
Naves estan rebotando daño sin tener modulo

**Como reproducirlo**
entrar a trial instance, comenzar la instancia con cualquier nave
1. entrar a trial
2. iniciar trial
3. atacar
3. las naves con las que atacas reciben daño reflectivo sin razon

**Comportamiento esperado**
no recibir daño por rebote sin modulos aparentes para esto

**Imágenes**
.
![image](https://user-images.githubusercontent.com/108841838/184887794-1944296c-8973-4dde-8c45-97f4e9aef693.png)

**Información Adicional**
.

**Comment by ToxicSSJ** [comment]
This is not a bug. There is a tech that reflect some armor damage.
