### ISSUE TITLE
no shootdowns after getting shootdowns

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#296]
**Describe the bug**
no shootdowns after getting shootdowns in pirates 
**To Reproduce**
fight and kill the pirate ships 

**Expected behavior**
SDs to be added to SD count thats in Rankings

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2809a.closed-alpha` version.
