### ISSUE TITLE
Bug de compra de Treguas, se eliminan

### ISSUE THREAD

**Issue by IronMaiden-Mike** [SuperGO2/supergo2-issues#298]
**Describe el bug**
Hago la compra de treguas mediante el catalogo con cheques, en primera no puedo usar las treguas y cuando hago refresh del juego se elimian de inventario.

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Abrir el catalogo
2. Comprar treguas con cheques
3. Cerrar el catalogo
4. Ir a inventario e intentar usar treguas.
5. Hacer refresh.
6. Ver el error

**Comportamiento esperado**
Al cerrar el catalogo no debería salir ningún error.

**Imágenes**
[Aquí agregaré enlaces a imagenes/video o también puedo arrastrar el contenido.](https://drive.google.com/drive/folders/1pUjZfmPIkr1Z_E2IC7dUrDBFJ0lc5ZcC?usp=sharing)

**Información Adicional**
Aquí debo agregar información adicional del bug.
Lo he replicado y siempre me quita los cheques y desaparecen las treguas

**Comment by IronMaiden-Mike** [comment]
Quedo pendiente Toxic, espero se pueda resolver muchas gracias!

**Comment by Warner231936** [comment]
¿Puede enumerar todo lo que estaba pasando cuando esto sucedió? ¿Qué edificios donde edificio? ¿Tenías investigación tecnológica en marcha? si es asi que fue? ¿Tenías módulos o cascos investigando? si es asi cuales? ¿Cuántos comandantes tiene en el centro de comandante y ha revisado su radar para ver si hay alguna flota que haya fallado en el modo de defensa? ¿Puede intentar comprar la tarjeta de tregua Adv y no usarla, recargar el cliente y ver si la tarjeta de tregua permanece en su bolso?

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2608a.closed-alpha` version.
