### ISSUE TITLE
Cant stage fleets to defend at ally plant 

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#299]
**Describe the bug**
Cant stage fleets to defend at ally plant 
**To Reproduce**
send fleets to def somewhere and get attacked  your fleets will still be at your base

**Expected behavior**
fleets to go where they are supposed to and not just glitch back to players base

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2008a.closed-alpha` version.
