### ISSUE TITLE
Corps wealth not spent on corps upgrade

### ISSUE THREAD

**Issue by irtusb** [SuperGO2/supergo2-issues#30]
**Notes:** Corps wealth is a resource spent when upgrading level, mall and others in a corp.
**How to reproduce:** reach required wealth for an upgrade, click upgrade and wait for it to finish.
**Expected:** at start or end (not sure) of an upgrade corps wealth should be consumed and deducted from current balance.

**Comment by spectuu** [comment]
Done!
