### ISSUE TITLE
Precondición no coincide

### ISSUE THREAD

**Issue by Gabrielelelele** [SuperGO2/supergo2-issues#300]
**Describe el bug**
Precondición no coincide

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Intentar usar The Sumo Bp

**Imágenes**

![Captura de pantalla 2022-08-18 132306](https://user-images.githubusercontent.com/110844634/185457606-d642d57a-ceb0-424d-8dd2-74c70edf4157.png)
![Captura de pantalla 2022-08-18 132257](https://user-images.githubusercontent.com/110844634/185457611-e6cb6aa5-bdc9-4262-8d5f-b481f82dfee0.png)

**Comment by ToxicSSJ** [comment]
This is a client bug. So we can't fix this.
