### ISSUE TITLE
pvp bug

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#301]
**Describe the bug**
when attacking player, sometimes the battle insta stops and your fleet somehow end up being in defencee mode there
then when recalled it take a very long amount of time to get them back
**To Reproduce**
send 1 fleet
hit target,
have it happen
recall fleet

**Expected behavior**
the battle to not just be over, battle sould play out and attacking fleets should never be defending 

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2809a.closed-alpha` version.
