### ISSUE TITLE
Corps rank

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#303]
**Describe the bug**
Very clear that its not wotking      Black-Star is higher level, higher member count, and higher donation points but less ranked
then the corps in 2nd and 3rd rank
**To Reproduce**
look in corps rankings
**Expected behavior**
be based off the 3 things mentioned above 

**Screenshots**
![7](https://user-images.githubusercontent.com/101828275/185776206-ac4f0a6a-2f35-4a61-a6ca-3f3c6dcd581b.PNG)
![8](https://user-images.githubusercontent.com/101828275/185776216-9eddd0ff-6228-4b30-a6b3-00da366f808e.PNG)

**Additional context**
at this moment the intergalactic counsel should be rank 1, as its level 10    they way it worked before was corps level 1st, then the points then the amount of members   to determine there placement on the corps ranking

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2608a.closed-alpha` version.
