### ISSUE TITLE
Visual bug / information cut off

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#306]
**Describe the bug**
in the ship designer, some of the diff modules are cut off 
**To Reproduce**
goto designer look at typhoon II in balii

**Expected behavior**
see the entire information message about it

**Screenshots**
![9](https://user-images.githubusercontent.com/101828275/185905984-ebb64d85-091e-41ab-bf56-5c9c553dd9ec.PNG)

**Additional context**

**Comment by ToxicSSJ** [comment]
This is because the client. So we can't fix this.
