### ISSUE TITLE
Radar in corps isnt functional?

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#315]
**Describe the bug**
Radar in corps isnt functional?
**To Reproduce**
have incoming to another player in corps, click into corps to try to see what it is 
notice there is no incoming, even tho there is 

**Expected behavior**
functional corps radar
**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2608a.closed-alpha` version.
