### ISSUE TITLE
after player leaves a corps, if they dont goto another corp, they can still see and send chat in corps chat

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#323]
**Describe the bug**
after player leaves a corps, if they dont goto another corp, they can still see and send chat in corps chat
**To Reproduce**
join corps
leave corps
notice you still can see and send green corps chat

**Expected behavior**
once you leave you cant send or read the corps chat 

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
