### ISSUE TITLE
Bug Cambio de corporacion

### ISSUE THREAD

**Issue by Alegher** [SuperGO2/supergo2-issues#324]
**No llega comandantes al correo al cambiar de corporación**
me cambie de corporación y no me llegaron los comandantes que tenia en el inventario de corporación.  se perdieron

**cambiando de corporación**
Pasos para replicar el bug siga estos pasos:
1. salir de la corporación
2. entrar a nueva corporación 
3. los comandantes del inventario no llega al correo.

**Comportamiento esperado**
llegue el correo con los comandantes 

**Imágenes**
![image](https://user-images.githubusercontent.com/111233923/187056982-8cc4fe5e-83a9-4d15-aace-d58860e9db41.png)

![image](https://user-images.githubusercontent.com/111233923/187057048-0946a318-02de-4032-80b4-36835fb57368.png)

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
