### ISSUE TITLE
Fleets stationed at RBP still available to use for instances 

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#325]
**Describe the bug**
Fleets stationed at RBP still available to use for instances 
**To Reproduce**
send fleet to an rbp
goto run instance
then see it still in the fleets you can send to instance

**Expected behavior**
fleets stationed at rbp be unusable for instance 

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0110a.closed-alpha` version.
