### ISSUE TITLE
Can attack a rbp in your possession during its war time

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#328]
**Describe the bug**
Can attack a rbp in your possession during its war time
**To Reproduce**
own rbp that goes into war mode
send to attack the rbp
see it work

**Expected behavior**
cant attack a rbp you already own 

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0110a.closed-alpha` version.
