### ISSUE TITLE
Using commander window resets fleet targeting

### ISSUE THREAD

**Issue by irtusb** [SuperGO2/supergo2-issues#33]
`Description` When in commander window there is the option to alter fleet target, range and reorder ships within. Pressing _save fleet_ button correctly saves new ship order, but resets target to min range and closest

`how to`
- edit a fleet using space base ui, set range and target to a value different from min range and closest target
- go to commander center
- select the commander that manages the fleet. ui shows the right range and target set beforehand
- click on save fleet button
- go to space base and hover the fleet, it will have range and target set to min range and closest

`expected` for it to work the same as editing a fleet via the space base interface

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.606b.beta-dev` version.
