### ISSUE TITLE
Una alianza puede atacar su propio Planeta de Recursos 

### ISSUE THREAD

**Issue by Supertoonix216** [SuperGO2/supergo2-issues#330]
**Describe el bug**
Una alianza puede tomar su propio PDR actual y lo puede volver a capturar por otra rotación

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Capturar el PDR 
2. Esperar a temrinar el tiempo de protección
3. Atacar tu planeta de recurso con tu misma alianza
3. Lo captura y tiene otro periodo de 72 h 

**Comportamiento esperado**
No poder atacar tu propio planeta de recursos 

![image](https://user-images.githubusercontent.com/112220775/187222046-81700ba3-2080-4674-bb37-67129b711408.png)

![image](https://user-images.githubusercontent.com/112220775/187222097-abc87f72-0208-4239-b4ea-893cb75fc94c.png)

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by skyprime17** [comment]
duplicate of #328

**Comment by ToxicSSJ** [comment]
Duplicate of #328.
