### ISSUE TITLE
Can retake your own rbp

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#332]
**Describe the bug**
Can retake your own rbp

**To Reproduce**
own a rbp
have it goto war mode
send and kill it
notice you have it for 72 hours again
**Expected behavior**
cant retake your own rbp,  let alone send at them

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0110a.closed-alpha` version.
