### ISSUE TITLE
NEGATOR CHIP is fully nonfunctional 

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#335]
**Describe the bug**
NEGATOR CHIP is fully nonfunctional 

**To Reproduce**
send cc to arena with no negator take note of dmg
resend cc to arena with even a HIGH level negator,
notice the DMG taken is identical to before adding ship

**Expected behavior**
for each shield module on my ships "in the effective stack" to have the additional negation "per module"

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0510a.closed-alpha` version.
