### ISSUE TITLE
Lag Supreme!

### ISSUE THREAD

**Issue by darlinxpro** [SuperGO2/supergo2-issues#336]
**Describe el bug**
the game totally freezes either after doing quests, entering planet under attack, entering resource planet, typing in global chat.

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Jugar durante 2 minutos
2. entrar a mision o algun planeta bajo ataque
3. volver a tu planeta
3. y ya estarias bugeado.

**Imágenes**
Aquí agregaré enlaces a imagenes/video o también puedo arrastrar el contenido.
![fast](https://user-images.githubusercontent.com/88944300/187766118-3419c128-e1a0-467b-98a4-51030ddd8351.png)
video from the lag complete
https://anonfiles.com/H0S1ja64y7/Super_Galaxy_Online_II_2022-08-31_15-18-50_mp4
**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
