### ISSUE TITLE
Missile Min Damage, Missile Max Damage are not working

### ISSUE THREAD

**Issue by imnikov** [SuperGO2/supergo2-issues#338]
**Describe the bug**
Missile Min Damage, Missile Max Damage and Transmissions chips are not working.

Chips damage:
1. Create 1 ship with 10 Refined Rocket Frame (210-280 dmg)(3150-4200 total)
2. Send it to attack Instance 1 
3. Do ~2800-3300 damage
4. Put blue chips of Missile Min and Max damage VI (Min +290, Max +330 damage)
5. Send it to attack Instance 1
6. Do same damage as before

Transmission Chip:
1. Send attack to somebody
2. Attack time is same as fleets without chips

**Expected behavior**
1. Ships with Min and Max Damage chips should be outputting a little bit more than double the original damage
2. Transmission time is the same with our without chip

**Comment by imnikov** [comment]
I did more testing, and the min and max damage chips add the damage to the enemy ships

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0510a.closed-alpha` version.
