### ISSUE TITLE
Pirate 2 BUG 

### ISSUE THREAD

**Issue by Supertoonix216** [SuperGO2/supergo2-issues#339]
**Describe el bug**
el pirate 2 esta bugeado, se mando 3 veces el numero de naves, no es visual 

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. seleccionar pirate
2. seleccionas al usuario
3. Mandarlos, se oprime el boten 2 o 3 veces
3. Ver el error, llegan muchos pirates

![image](https://user-images.githubusercontent.com/112220775/188055779-c233d07b-3eb7-4ff7-91f8-534ab5b717e4.png)

**Comportamiento esperado**
Al cerrar el catalogo no debería salir ningún error.

**Imágenes**
Aquí agregaré enlaces a imagenes/video o también puedo arrastrar el contenido.

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0510a.closed-alpha` version.
