### ISSUE TITLE
Ship Speed Up

### ISSUE THREAD

**Issue by DevTruce** [SuperGO2/supergo2-issues#34]
Description: when you try to speed up the ship building process using mp, it does not work

How to reproduce: try and speed up your ship building 

Expected behavior: you should be able to increase the ship building speed 

Video 1:  https://jmp.sh/iRujziZ

**Comment by irtusb** [comment]
AFAIK it is not implemented yet

**Comment by Truce-R** [comment]
My mistake, I didn't have much time last night so I didn't get a moment to view the google sheet for any updates.

**Comment by Truce-R** [comment]
> AFAIK it is not implemented yet

My mistake, I didn't have much time last night so I didn't get a moment to view the google sheet for any updates.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.606b.beta-dev` version.
