### ISSUE TITLE
Cant build a legal build

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#340]
**Describe the bug**
Cant build a legal build
**To Reproduce**
make the ship in the screenshot, 
try to start building them
notice nothing happens and they wont build

**Expected behavior**
the ships to build

**Screenshots**
![11](https://user-images.githubusercontent.com/101828275/188103751-e6d02270-4956-4d0e-a815-9151d87ec0b4.PNG)

**Additional context**

**Comment by ToxicSSJ** [comment]
Can't reproduce
