### ISSUE TITLE
Mail icon bug 

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#342]
**Describe the bug**
Mail icon bug 
**To Reproduce**
not 100% sure how to make it happen, but after every reload im getting the mail icon, but when i press it
there is no mail in the mailbox 

**Expected behavior**
mail icon to only show up if there is mail or if there is mail for it to show in the mailbox 

**Screenshots**
![12](https://user-images.githubusercontent.com/101828275/188241974-2b20aa66-d6c2-4e4e-920f-46168a9d4875.PNG)
![13](https://user-images.githubusercontent.com/101828275/188241994-ff3ef000-aca6-48d9-a1bf-dccd2b63d28c.PNG)

**Additional context**
was playing and radomly the mail icon popped up, i had no items in the AH and was not running instances, so no idea why id have mail,    reloading the client just brings the mail icon back.

**Comment by ToxicSSJ** [comment]
Need more information, step by step how to reproduce it
