### ISSUE TITLE
Fleet creation lost ships

### ISSUE THREAD

**Issue by PoH98** [SuperGO2/supergo2-issues#344]
**Describe the bug**
Fast create fleet bug causing negative ships and ships lost

**To Reproduce**
1. Go to Military tab
2. Click on Create Fleet
3. Repeating create fleets fast and make sure having last fleet with not enough ship numbers (like mine is 7200 ships and creating 4 fleets, each having 1900 ships in it, hence I get -400 ships and last fleet's ships which suppose having 1500 will be gone forever into void)

**Expected behavior**
The system should shows 1500 ships and unable to put 1900 to the fleet, no ships should be gone into void

**Screenshots**
None

**Additional context**
Creating fleets now also bugged as hell while you selected the commander previous fleet but still shown while creating next fleet. All data is just expired and not latest causing above bug

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
