### ISSUE TITLE
desaparición de naves y naves negativas

### ISSUE THREAD

**Issue by hito19** [SuperGO2/supergo2-issues#346]
**Describe el bug**
Una descripción clara y concisa de que hace el bug.

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. crear flotas
2. cargar flota prediseñada
3. cerrar creación de flotas 
4. ver que no se creó una flota nueva 
5. entrar a creación de flotas nuevamente y ver naves en negativo 

**Comportamiento esperado**
deberían aparecer las naves o la flota creada y no salir en negativo la cantidad de naves

**Imágenes**
![image](https://user-images.githubusercontent.com/65687925/188331789-a7f5eefd-ed91-41f4-afe6-afb9c685f290.png)
![image](https://user-images.githubusercontent.com/65687925/188331817-7d1c1030-d7d4-4601-a505-bd78c8d34714.png)
![Uploading image.png…]()

**Información Adicional**
baje de top 10 al 20 perdiendo 8k de naves tipo daybreack-3

**Comment by skyprime17** [comment]
duplicate of #344
