### ISSUE TITLE
Inventory Viewing 

### ISSUE THREAD

**Issue by DevTruce** [SuperGO2/supergo2-issues#35]
Description: when you try to view you inventory select categories, it does not function correctly

How to reproduce: try and view your inventory select categories 

Expected behavior: you should be able to view each tab once you click the selected category icon

Video 1: https://jmp.sh/9GWyUae

**Comment by ToxicSSJ** [comment]
I can't reproduce this bug

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.514b.beta-dev` version.
