### ISSUE TITLE
[gamebreaking] Ref. Plate not working properly, bugs combat instance

### ISSUE THREAD

**Issue by imnikov** [SuperGO2/supergo2-issues#351]
**Describe the bug**
This is beyond my understanding. Ref plate III reflects 100% of damage (minimum). Has no cd. Bugs out combat instance.

**To Reproduce**
1. Equip ref plating
2. Get structure damage
PSA: My tech defense tree is only missing Stability Mastery (0/3)

vids:

https://youtu.be/uBCG8RnslvY
https://youtu.be/lSZHgsM-f8Q

good luck with this one devs

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2809a.closed-alpha` version.
