### ISSUE TITLE
Pirates level 3 is broken

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#355]
**Describe the bug**
Pirates level 3 is broken

**To Reproduce**
launch p3
notice it shows nothing in the WC about you starting them
fight the pirates for one round, 
notice then fight just stops, and dont move on to the next round

**Expected behavior**
pirates level to to be dropped and be in the wc and be abel to finish it
**Screenshots**

**Additional context**
it did not take the 1 use you get a day to run pirates, i was abel to run level 2 right afterwards

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0510a.closed-alpha` version.
