### ISSUE TITLE
People can't PM me because of my Name

### ISSUE THREAD

**Issue by zRulerr** [SuperGO2/supergo2-issues#357]
**Describe the bug**
My Name is not clickable in the chat, therefore i am also not PM'able

**To Reproduce**
1. Ask me to write in WC
2. Try to click on my name

**Expected behavior**
No context menue will open

**Additional Context**
Doesnt work in all Chat Channels

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2110a.closed-alpha` version.
