### ISSUE TITLE
Truce Cards dont work

### ISSUE THREAD

**Issue by WallLicker** [SuperGO2/supergo2-issues#359]
**Describe the bug**
Using an Advanced truce card doesnt do anything except wasting the item itself and also normal Truce cards dont work.

**To Reproduce**
1. Go to Bag
2. Click on Any Truce card

**Expected behavior**
Be protected x.x

**Comment by PoH98** [comment]
More details: 
Actually it did works, except you have fleets INSIDE INSTANCE. So you need stop instance to use the truce cards

**Comment by WallLicker** [comment]
Oh that might be it, wich still doesnt make sense but ok now i know, tnhx

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
