### ISSUE TITLE
he3 spent in instance is restored at instance's end

### ISSUE THREAD

**Issue by irtusb** [SuperGO2/supergo2-issues#36]
`How to`
- fill a fleet with he3
- use it in an instance
- watch he3 supply go down during instance
- after instance ends naturally or by cancelling, ship has full he3

`Expected` he3 spent should remain spent after finishing an instance or stopping it midway

**Comment by ToxicSSJ** [comment]
Please use the right issues format. [Check it here](https://github.com/SuperGO2/supergo2-issues#report-bug)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.514b.beta-dev` version.
