### ISSUE TITLE
Maletiz is undertuned

### ISSUE THREAD

**Issue by 0Nimroth** [SuperGO2/supergo2-issues#360]
**Describe the bug**
Maletiz has too low proc rate, currently seeming to reach at most around 35% max with a fully gemed 9*.
It seem to use dodge only for proc but it still have the stat requirement as if it was dodge/elec.

**To Reproduce**
1. Send to an instance on tanks
2. Count the number of procs and non-procs.
3. Compare to the intended proc rate.

**Expected behavior**
In the original game Maletiz used dodge only for proc unlike what the description that says and would max out at around 85% proc rate.
Alternatively if it used dodge/elec as the description suggest you would have been able to get around 60% proc rate.

**Additional context**
To fix it you would probably have to either cut the required stats in half if you want it to match the actual proc rate in the original game.
Alternatively you could make it dodge/elec, which would still be lower than the original proc rate but better than it is now.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
Now maletiz used dodge/electron.
