### ISSUE TITLE
GAME NEITHER BROSWER OR APP WONT WORK 2 DAY IN A ROW

### ISSUE THREAD

**Issue by calacavenezolana** [SuperGO2/supergo2-issues#363]
I cant join the game, There is no more info about it, It is just I cant. Please fix it...
![2cap](https://user-images.githubusercontent.com/108645818/190307389-b7b101a2-a5af-42e3-a163-5a07cb6354d2.PNG)
![1cap](https://user-images.githubusercontent.com/108645818/190307392-9c8bf2fd-262c-4c8f-882c-778f4400879f.PNG)

**Comment by ToxicSSJ** [comment]
Please use the right format.
