### ISSUE TITLE
Magneto Pulsar BP doesnt exist

### ISSUE THREAD

**Issue by NonsensedudeROFL** [SuperGO2/supergo2-issues#364]
Hi guys officially in this game the blueprint of magneto Pulsar should be given to us when we built 8 warships but i have now owned thousands of them but it never showed up, is there any way you can fix this and give us the BPs? some of us also had same issues and could not progress in the Directional weps in this game
My username for this game is 'Nonsense'
![image](https://user-images.githubusercontent.com/113620024/190443311-bcaab636-830c-4aac-b15f-13874f092e5e.png)

![image](https://user-images.githubusercontent.com/113620024/190444608-f9d95d03-58dd-42af-9a65-137e52aa2fe1.png)

**Comment by ToxicSSJ** [comment]
Please follow the right format.
