### ISSUE TITLE
no login at all

### ISSUE THREAD

**Issue by KillAwesome** [SuperGO2/supergo2-issues#366]
**Describe the bug**
you just click on the game in the app and donna appears thats it (same goes for the website version)

**To Reproduce**
1.click on app/go to website
youll just see donna nothing else

**Expected behavior**
i expected to see the usual login screen like how many players, planets section but nothing.

**Screenshots**
![this sucks](https://user-images.githubusercontent.com/109487703/190596973-f27f36b8-9314-4b04-b35b-2679fb707b2b.PNG)
![website version](https://user-images.githubusercontent.com/109487703/190597553-97e456e6-bf5f-4173-a5c4-68e422fe37c7.PNG)

**Additional context**
it was working fine until the tournament was announced which brought a new update im pretty sure that is causing all this, im not sure but it could be the case

**Comment by PoH98** [comment]
For this actually it isn't just login issue lol, it is ALL request which involved with the server. Some of it will failed with code 200 if you inspect element and watch the network tab. It just failed randomly

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2709a.closed-alpha` version.
