### ISSUE TITLE
No llegan solicitudes para entrar a nuestra corp

### ISSUE THREAD

**Issue by Gabrielelelele** [SuperGO2/supergo2-issues#367]
**Describe el bug**
Cuando alguien manda una solicitud para unirse a la corp Destiny, no aparece en la ventana de "Recruit"

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Alguien fuera de la corp manda apply 
2. No aparece en la ventana para aceptarle

**Comportamiento esperado**
Que aparezca el apply para poder aceptarlo en la corp

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2809a.closed-alpha` version.
