### ISSUE TITLE
Truce Cards not working

### ISSUE THREAD

**Issue by Gloster173** [SuperGO2/supergo2-issues#369]
**Describe the bug**
Truce Cards sometimes can be used and not apply truce status to planets. This occurs only when fleets are in an instance.
**To Reproduce**
1. Send fleets to any instance
2. Apply truce Card in bag
3. Truce card will be used, but account will not be truced.

**Expected behavior**
Truce Cards to apply when fleets are in instances.

**Comment by deltaflyer97** [comment]
bought two advance truce cards both have failed to work and disappeared out of my bag

**Comment by ToxicSSJ** [comment]
Duplicate of #359.
