### ISSUE TITLE
client freeze when opening huma chips manager

### ISSUE THREAD

**Issue by irtusb** [SuperGO2/supergo2-issues#37]
`description` opening the chips manager makes client stop responding to mouse input although it continues working (there is normal network activity)
`how to` open huma chips manager button and watch unresponsive client
`expected` at least an empty window. i know chips are not implemented yet
`note` this has been commented before but not as an issue

**Comment by ToxicSSJ** [comment]
Please use the right issues format. [Check it here](https://github.com/SuperGO2/supergo2-issues#report-bug)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1006b.beta-dev` version.
