### ISSUE TITLE
Daño de Penetración mal calculada

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#370]
**Describe el bug**
Actualmente tu Penetración se basa en la cantidad de daño que le realizas a los escudos
Ejemplo el 15% de Penetración bala 
Esto significa que si tus escudos niegan la totalidad del daño, no habra daño de Penetración 

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Desarrolar la investigación de bala o laser de Penetración 
2. Enfrentar a una nave tanke sin llegar a tocarle los escudos 
3. No hay daño realizado en la estructura 
3. Ver el error.

**Comportamiento esperado**
Si hay Penetración, esto significa que habra un % de daño adicional del daño total realizada en la estructura

**Comment by darlinxpro** [comment]
Tienes que saber que para hacer que la estructura no sufra daño tienes que tener full en investigación y añadidos módulos de estructura en la nave.
