### ISSUE TITLE
Mal activación del QRA y RP 

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#371]
**Describe el bug**
Quick reaction armor y reflective plate, no se activan siempre que se ocasione daño a la estructura, únicamente se activan cuando los escudos han bajado a 0
Esto significa que por ejemplo la penetración o la habilidad de el legendario Marcus que ignora los escudos y modulos de escudos, no estaría activando defensas adicionales como el Qra o la placa

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Atacar o ser atacado por daño de Penetración 
2. Recibir daño en la estructura, teniendo aún escudos base
3. Qra o rp no se activan
4. Una forma facil de replicarlo es en trial 10 donde los Marcus abundan

**Comportamiento esperado**
Cualquier daño que se realize en la estructura incluso todavía teniendo escudos base activaran la totalidad de modulos defensivos de la estructura

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2809a.closed-alpha` version.
