### ISSUE TITLE
Reflective plate infinita

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#372]
**Describe el bug**
La Reflective plate no tiene enfriamiento, rompiendote la cola golpe tras golpe

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Golpear naves que tengan el modulo Reflective plate 
2. Disparo tras disparo, ronda tras ronda la rp no se ira
3. Forma facil de reproducirlo es en casi todas las fases de trial

**Comportamiento esperado**
Rp deja dejara de funcionar una vez activada, varia su enfriamiento segun las investigaciones de defensa

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2809a.closed-alpha` version.
