### ISSUE TITLE
Daedalus Control Sistem se activa aun sin he3

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#374]
**Describe el bug**
Daedalus Control Sistem con un gasto de 0.05 por nave sigue funcionando luego de que el valor de he3 sea 0, dificultando la limpieza de flotas
**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Atacar naves con Daedalus
2. Esperar a que se vacien de he3
3. Daedalus sigue funcionando

**Comportamiento esperado**
Una vez se agote el combustible Daedalus dejara de activarse

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2809a.closed-alpha` version.
