### ISSUE TITLE
Can't dismiss dead commons.

### ISSUE THREAD

**Issue by 0Nimroth** [SuperGO2/supergo2-issues#375]
**Describe the bug**
It seems that you currently need to revive a dead common before you can dismiss it.

**To Reproduce**
1. Have a dead common
2. Dismiss it and refresh the game.
3. See that the common is still in your comm center.
4. Revive it before dismissing it again and then refresh, now it is gone.

**Expected behavior**
You should be able to dismiss commons even if they are dead, instead of having to waste revival cards on them.

**Additional context**
I've not tried with other commanders but they might have the same problem.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2809a.closed-alpha` version.
