### ISSUE TITLE
Bug al Reclamar la caja de recompensas (desaparece)

### ISSUE THREAD

**Issue by Reyjorge1703** [SuperGO2/supergo2-issues#377]
** El bug consiste en que al reclamar la caja de recompensas, desaparece reinicias el juego vuelve aparecer , lo reclamas y vuelve a desaparecer xD **

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Reclamar la caja de recompensas 
2. Desaparecera la caja 
3. Reiniciar el juego
3. Ver el error.

**Comportamiento esperado**
Al reclamar la caja me deverian de dar la recompensa y seguir con la siguiente recompensa 

**Imágenes**
En este tipo de bug es imposible capturarlo xD

**Información Adicional**
Aveces la caja de recompensas solo se bugea apartir de las recompensa de 1 hora en adelante 
:)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1810a.closed-alpha` version.
