### ISSUE TITLE
Error al crear cuenta 

### ISSUE THREAD

**Issue by KarasxD** [SuperGO2/supergo2-issues#382]
Qué tal toxicssj

No puedo o más bien no me deja crear cuanta, registro todo correctamente incluso me llega correo de confirmación y al momento de iniciar sesión no admite las credenciales que ingrese en el registro.

Email-piloto.mushroom.electronik@hotmail.con
Username- Karas 

Saludos!

**Comment by ToxicSSJ** [comment]
Este no es el lugar para este error, por favor cree un ticket en nuestro discord.
