### ISSUE TITLE
Necesito ayuda 

### ISSUE THREAD

**Issue by ImmortalLunatic** [SuperGO2/supergo2-issues#389]
Hola ,buen dia no me logra cargar muy bien el juego . Mensajeria , no se visualiza la construcion ,etc
Adjunto fotos
![Screenshot_20221002-191719_Puffin](https://user-images.githubusercontent.com/114887893/193482975-f05500a4-2286-4a38-a449-4dce77a0ab6e.jpg)

![Screenshot_20221002-191702_Puffin](https://user-images.githubusercontent.com/114887893/193482986-72e454fb-5781-4ec0-ac78-7a5bfa0d20a4.jpg)
![Screenshot_20221002-191702_Puffin](https://user-images.githubusercontent.com/114887893/193482992-a3a61c8b-f747-44f4-ba98-b6dcc8cd8f82.jpg)
![Screenshot_20221002-192420_Puffin](https://user-images.githubusercontent.com/114887893/193483138-11f1f695-4034-46cb-9ae8-d982bd2091d9.jpg)
Estare atento a su respuesta gracias. :)

**Comment by ToxicSSJ** [comment]
Please follow the Issues format.
