### ISSUE TITLE
Compound Center merging crash

### ISSUE THREAD

**Issue by NatalieWilsher** [SuperGO2/supergo2-issues#390]
When i entered the compound center and went to the merging EX tab, I started merging Giant Triads then I started to merge Guardian Triads. This normally wouldn't be an issue but the compound center didn't synchronize with the amount of gold I have on my account, so it still thought I had the same amount as when I started. It allowed me to attempt to merge the 2 Guardian Triads but instantly froze the game. I do believe this synchronization isn't limited to just the compound center as I have seen it say in another building before that I had resources still even though I just used them, though this corrected after leaving the building and returning (apologies for forgetting to report that bug then).

As for what the expected behaviour should be, once my gold had run out it should not have let me attempt to merge gems and the "Merge" button should have been greyed out and the "cost of the merge in gold value" above the button be in red.

**Comment by ToxicSSJ** [comment]
Please follow the right format.

**Comment by ToxicSSJ** [comment]
Your Issue is good explained, but it's important to use the right format (it's a form that you can fill), just click on "New Issue" and choose the language of the template. Thank you for your report!
