### ISSUE TITLE
Unbinding cards from bag does not work

### ISSUE THREAD

**Issue by DeaJae** [SuperGO2/supergo2-issues#394]
**Describe the bug**
Unbinding a Commander Card results in 1 card disappearing from the locked stack (if there is more than 1), MP does not go down, nor does the unlocked card appear on the existing unlocked card stack.
Relogging shows the locked card back in the locked stack/state.

**To Reproduce**
Steps to reproduce the behaviour:
1. have 1 or more unlocked cards in the bag.
2. Click on 'unbind'
3. Check the MP amount and whether it's produced the unlocked card.
4. panic?

**Expected behaviour**
The card appears as unlocked.

**Additional context**
Not tested if it happens without existing unlocked version in bag.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1610a.closed-alpha` version.
