### ISSUE TITLE
Rocky keeps it's buff between rounds.

### ISSUE THREAD

**Issue by 0Nimroth** [SuperGO2/supergo2-issues#395]
**Describe the bug**
Currently the buff from Rocky's ability persists between rounds.

**To Reproduce**
1. Make sure you have Shield Penetration done in ballistic science.
1. Fleet Rocky on 9 stacks of ships with 1 ballistic gun and target min dura.
2. Send it in to arena against a tank stack without energy armour mods and take note of how much damage Rocky does per hit.
3. Repeat step 2 but this time also with the opponent sending a small fleet of 9 stacks of 1 ship alongside the tank.
4. Notice that after killing the small fleet Rocky in following rounds also hit harder than in step 2 against the tank fleet, without having to kill a stack.

**Expected behavior**
The buff from Rocky's ability is only mean to last for 1 round, not be kept for following rounds without having to be reapplied.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1810a.closed-alpha` version.
