### ISSUE TITLE
glitch after completing creation of a new fleet

### ISSUE THREAD

**Issue by Unthwarted01** [SuperGO2/supergo2-issues#396]
I was creating a fleet with Daybreaks I had bought for my Rocky as commander. When I was done making the stacks and went out of the fleet builder, a pirate commander 7 star Gastaf showed up as commanding that fleet.  I couldn't click on it.   The fleet was frozen. Thinking it was a temporary glitch, and I just had to refresh, I closed the PC program and reopened, and the fleet and ships were completely gone. They are not in storage or anywhere in the starbase, but thankfully at least, my Rocky was back in the command center.  But the ships I had bought are completely non-existent now.  I created a fleet afterwards for Rocky with different ships, and everything went as it normally does.

**Comment by ToxicSSJ** [comment]
Please use the right format.
