### ISSUE TITLE
Email Address not found - "support@supergo2.com"

### ISSUE THREAD

**Issue by AWESOME143** [SuperGO2/supergo2-issues#398]
**Describe the bug**
Try to email and apply to be in your team, but email Email Address may not exist and so I will send my application through here.

Subject: Application for be your next teammate - Jonel Dave Ismil - CV

[JONEL DAVE ISMIL - CV.pdf](https://github.com/SuperGO2/supergo2-issues/files/9728490/JONEL.DAVE.ISMIL.-.CV.pdf)

Hi Super GO2 Team,

I'm a player/gamer/fan of GO2. I'm a freelancer and want to join your team as your contact/help/coordinator/social media post maker/transactions support/chat support Facebook & Discord. I've 5 years of experience assisting clients. Feel free to check my attached CV. Thank you.

Contact:
email: [ismiljd@gmail.com](mailto:ismiljd@gmail.com)
discord: AWESOME_v2 #0614

**To Reproduce**
just send an email

**Expected behavior**

**Screenshots**

**Additional context**

![email address not found](https://user-images.githubusercontent.com/115186939/194414811-f706d6b1-e119-45ee-84f0-a575bdb57d22.PNG)

**Comment by ToxicSSJ** [comment]
Sorry sir, you can contact us via tickets in our discord. Thanks for your interest.
