### ISSUE TITLE
Negative Resource values

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#4]
Description: Negative resource values on the client (also doesnt show mp)
How to reproduce: Get over 2,5 billion of 1 resource and it shows as negative
Expected behavior: Correct amount of resource should show 
![image](https://user-images.githubusercontent.com/102363858/160130004-2afc3a86-045b-44a5-b44d-20ce5963fd0e.png)

**Comment by ToxicSSJ** [comment]
This bug was fixed `V2022.35b.beta-dev`.
