### ISSUE TITLE
Galaxy colour palette

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#40]
description: Wrong colour palette on planet names
expected: Colour should be only visible on your planet
How to reproduce: Literally logged in
![2022-05-28](https://user-images.githubusercontent.com/102363858/170835071-389b57ad-2498-4299-9a91-3ff8f13bb5aa.png)
 and it was there xd

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1006b.beta-dev` version.
