### ISSUE TITLE
Bart skill bug

### ISSUE THREAD

**Issue by PoH98** [SuperGO2/supergo2-issues#402]
**Describe the bug**

**To Reproduce**
1. Get a Bart and it is only fleet
2. Try make it's skill activation rate high enough
3. Go into arena and find an opponent
4. Bart will active its skills even there is only him left, causing opponent skip his turn

**Expected behavior**
If there is only Bart left on field, no skills will be actived

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2811a.closed-alpha` version.
