### ISSUE TITLE
Electronic Barrier is reflecting structure damage.

### ISSUE THREAD

**Issue by 0Nimroth** [SuperGO2/supergo2-issues#403]
**Describe the bug**
Currently the Electronic Barrier defensive tech is reflecting 10% of all damage after shields are down.

**To Reproduce**
1. Make sure you have Electronic Barrier researched.
2. Form a fleet of high structure ships( such as novas ark or black hole) without any guns, negation or reflective modules. 
3. Send it into arena against a fleet with guns.
4. Notice it still reflects damage after shields are down and only structure is left.

**Expected behavior**
Electronic Barrier is only meant to reflect 10% of the damage that is dealt to shields, and should have no effect when shields are down.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1610a.closed-alpha` version.
