### ISSUE TITLE
Laser Tech. Weakness Detection provides too much Hit Chance

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#404]
**Describe the bug**
When Weakness Detection procccs laser weapons gain too much maximum hit chance.

**To Reproduce**
1. Go to a battle where laser weapons are used/Example Trial 10
2. Watch your ships getting raped by lasers/ Robert bullies you
3. Seethe and Cope about it.
4. Complain to Toxic
5. Get laughed at.
6.  : C

**Expected behavior**
Laser not OP, pls nerf.

**Screenshots**
![LaserStrong](https://user-images.githubusercontent.com/108492773/194771677-252fed98-6535-4b21-babd-7eee78dc6f8f.JPG)
![LaserWeakness](https://user-images.githubusercontent.com/108492773/194771678-b1762c98-6094-4cb3-950c-0274b2b85c2a.JPG)

**Additional context**
Im getting bullied

**Comment by ToxicSSJ** [comment]
I tried a lot, but it doesn't for me
