### ISSUE TITLE
Regalo ez

### ISSUE THREAD

**Issue by sparta-1** [SuperGO2/supergo2-issues#405]
**Describe el bug**
Una descripción clara y concisa de que hace el bug.
no puedo reclamar el regalo EZ que dan cada cierto tiempo, cuando lo toco para que de el premio solamente desaparece y no sigue contando tiempo, no puedo reclamar las demàs recompensas, soy Sparta
**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Abrir el catalogo
2. Comprar algo
3. Cerrar el catalogo
3. Ver el error.

**Comportamiento esperado**
Al cerrar el catalogo no debería salir ningún error.

**Imágenes**
Aquí agregaré enlaces a imagenes/video o también puedo arrastrar el contenido.

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2010a.closed-alpha` version.
