### ISSUE TITLE
Cant  attack

### ISSUE THREAD

**Issue by Lightig** [SuperGO2/supergo2-issues#406]
**Describe el bug**
Cuando quiero atacar un planeta no puedo hacerlo desde el darle click en el planeta tengo que buscarlo en el ranking para que aparezca la ventana para poder atacarlo
**Como reproducirlo**
Sinceramente no se el  porque pero se produce pero cuando doy click en el planeta no me aparece nada, le doy click y se mueve el mapa no me deja atacar, el unico modo es que lo busque por medio de los rankings y ahi me aparece la pestaña que dice entrar, atacar y todo eso, ahi es cuando puedo atacar y para entrar al planeta del mismo modo en los rankings
![1](https://user-images.githubusercontent.com/115441096/194796045-831c8ead-ea64-4632-b4d7-fbb738a4a8dc.PNG)
![2](https://user-images.githubusercontent.com/115441096/194796051-099be1de-cf3e-4949-adba-f6db751d2004.PNG)

**Comportamiento esperado**
que al dar click en el planeta me aparezca las opciones de entrar o atacar y todo eso

**Imágenes**

**Información Adicional**

**Comment by ToxicSSJ** [comment]
Esto es un bug viejo del cliente de flash.
