### ISSUE TITLE
Allied planets in galaxy map

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#41]
Allied planets dont show up in the galaxy map
 They are supposed to have a special symbol in the map
-Open the galaxy map in a corp with allies

![2022-06-12](https://user-images.githubusercontent.com/102363858/173248922-8f631f58-a5d1-4cc2-a550-93fb4460d3e0.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
