### ISSUE TITLE
Me banearon 

### ISSUE THREAD

**Issue by freddii121** [SuperGO2/supergo2-issues#410]
Me banearon la cuenta :c, porque 2 personas entramos
Tengo un internet y entramos en la mima computadora y nos dieron baned

**Comment by ABanC1001** [comment]
Los issues de github son para reportar bugs del juego, lo que necesitas para arreglar este tipo de problemas es un ticket, en el canal #alpha-support del discord

**Comment by freddii121** [comment]
Por favor desbaneame :c quiero jugar

**Comment by XxpachuxX** [comment]
Ayuda porfavor por q me suspendieron la cuenta?
