### ISSUE TITLE
The Dictators Scroll Gone

### ISSUE THREAD

**Issue by GodValley25** [SuperGO2/supergo2-issues#422]
**Describe the bug**
When i tried to merge The Disctators Divine Command 7* the sroll just gone
Before merged i look on initial chance its 70% so i use memory chip to increase the precentage by 30% to 100%
But when i merged nothing happen that merged tab just gone and 2 my comms which is 7* rayo and 7* titan just go to bag
If fail i should see the notif on fail but no notif appear even succes or fail notif.

**To Reproduce**
1. Go to bag
2. Click on scroll The Dictators and clicked memory chip to increase the chance succes 
3. Click merge but nothing happen , no notif and my comms just back to the bag

**Expected behavior**
Please toxic at least give me one more scroll dictators. I was buy that scroll for 325mp
ID : 130 
Nickname : GodValley

**Screenshots**
![image](https://user-images.githubusercontent.com/115976308/196112926-523d9477-bc18-4151-86b6-572cce86b3e1.png)
![image](https://user-images.githubusercontent.com/115976308/196113074-f9dc7976-5a44-4267-956c-f918c24b8332.png)

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1810a.closed-alpha` version.
