### ISSUE TITLE
Can't Open Mail

### ISSUE THREAD

**Issue by Aniketoser** [SuperGO2/supergo2-issues#423]
**Describe the bug**
After I click on mail, I have lost connect on the game

**To Reproduce**
1. Go to 'After refresh the game'
2. Click on 'mail'
3. After i click on mail I have lost connect

**Expected behavior**
Please Fix i just need item in my mail
ID: 364
Name: Aniketos

**Screenshots**
![2](https://user-images.githubusercontent.com/115983851/196136973-49de67bd-54f6-4806-a623-dd03300a9585.PNG)
![3](https://user-images.githubusercontent.com/115983851/196137028-09e83f43-27a3-4a36-8933-d1adc750cecb.PNG)

**Comment by Aniketoser** [comment]
How this 3 mail coming from? and look at date
![4](https://user-images.githubusercontent.com/115983851/196153672-87d4c064-dad5-4351-b787-9b7857267b1a.PNG)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1810a.closed-alpha` version.
