### ISSUE TITLE
Error with merging 9* Divine 

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#424]
**Describe the bug**
Error with merging 9* Divine FF, a player used a 8* Marcus and a 9* Wayne to get a 9* FF

**To Reproduce**
1. have a 8* marcus, 9* wayne and a FF scroll 
2. click to merge
3. notice you got a 9* and not a 8*

**Expected behavior**
Rounds down to the lower of the 2 different * ranks as there is no middle with a 8-9 *
**Screenshots**
If applicable, add screenshots
![zzzzz1111111](https://user-images.githubusercontent.com/101828275/196290408-3e8fc932-8719-4bd4-83eb-10a0a802c46d.PNG)
 to help explain your problem.

**Additional context**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1810a.closed-alpha` version.
