### ISSUE TITLE
the scroll of dictators disappeared

### ISSUE THREAD

**Issue by zean2zn2** [SuperGO2/supergo2-issues#425]
**Describe el bug**
the scroll of dictators disappeared
I used the dictators parchment and after merging my lightning r4 and titan r4 I put a 30% chip on it to make sure 100% that the fusion was successful, then I clicked on merging and nothing happened and I threw myself into the inventory and the scroll of dictators disappeared

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Inventory
2. use the parchment
3. place cards and chip
4.merge and nothing happens and it votes you to the inventory and the scroll disappears

**Comportamiento esperado**
 Let the scroll do the fusion of commanders
**Imágenes**

![titan](https://user-images.githubusercontent.com/116056263/196344631-d343cb16-54f7-4eca-8bd8-3f2ac41719ca.png)

**Información Adicional**
Dictators scroll disappears when used
CHINOLINK-SN-  ID 259

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1810a.closed-alpha` version.
