### ISSUE TITLE
account has been suspended

### ISSUE THREAD

**Issue by EricTran1101** [SuperGO2/supergo2-issues#426]
I have just created one more account and I've got a message that My account has been suspended. I checked #rules but I couldn't find that I can not have more than one account on the same PC. Is there any solution ?

**Comment by zRulerr** [comment]
![Screenshot_20221018_171904](https://user-images.githubusercontent.com/108607807/196472813-2e689bd2-ea3e-4b8b-a95f-1af89d68824b.jpg)

**Comment by EricTran1101** [comment]
so,
 is there any solution?

**Comment by zRulerr** [comment]
Open a Ticket in #Alpha-support.

Maybe the mods will show some mercy ;)
