### ISSUE TITLE
Leo 1 PP stats

### ISSUE THREAD

**Issue by plemos6664** [SuperGO2/supergo2-issues#427]
Leo 1 6* PP is processing against a 9* RoD. Factoring in the possibility of max gems the max stats of the 6* PP is 1982 combined. My RoD has max stats of 1990, so the 6* PP should never process against my RoD, however it does. Please look into the balancing of divines within Leo 1 (and constellations as a whole) as they are not realistic.

**Comment by ToxicSSJ** [comment]
Please use the right Issues format.
