### ISSUE TITLE
Galaxy view does not display Instance completed

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#43]
Left clicking on a players planet in Galaxy view does not display Instance completed.
<img width="34" alt="instncelevel" src="https://user-images.githubusercontent.com/102439239/175141639-e7f7082f-edcf-416a-bcd4-e8167289e2b5.png">

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.3006b.beta-dev` version.
