### ISSUE TITLE
Fleets not entering instances, screen freezing 

### ISSUE THREAD

**Issue by TashuliT** [SuperGO2/supergo2-issues#430]
**Describe the bug**
after my bug last night, had someone else's fleer on top of mine and couldn't use mine at all, not even fuel it. (This was resolved somehow). 
Now when i try to run instances, after selecting the fleets and clicking send, nothing is happening. Space base is frozen and I either have to refresh the game or go to ground base and back again to space base just to find my fleets still in my base and not in instace. 
After several attempts it puts the fleets into instance but after couple shooting animations, the game freezers completely and I have to refresh it.
I've done this like 8times just to start and see some of the instance how's working.

**To Reproduce**
1. Go to space base
2. Click on instance you try to run, select fleets and click send.
3. After sending nothing happens (several tries to actually start an instance)
4. See error - frozen screen both in instance and/or space base

**Expected behavior**
After selecting the fleets to send to instance, click send and get the instance battle screen (not be left in space base), where you can watch the shooting animations without problem.

**Screenshots**

**Additional context**
My space base is acting like is not mine? Not sure...

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2010b.closed-alpha` version.
