### ISSUE TITLE
kazati bug, no funciona

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#432]
**Describe el bug**
Nave capitana, kazati, no funciona su efecto

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. diseñar naves kazati
2. crear naves kazati
3. crear flota con naves kazati, estando con otras naves o solas.
3. Al pasar los turnos, no regenera escudos, no tiene daño adicional, no rebota mas daño

**Comportamiento esperado**
Deberia penetrar un % de escudos enemigos, rebotar un % adicional de daño y regenerar un % de escudos por turno

**Imágenes**
.

**Información Adicional**
.

**Comment by 0Nimroth** [comment]
All of the bonuses are working for me, at least with lvl1 Kazati.

**Comment by skyprime17** [comment]
lvl 3 Kazati also works in instances or humaroids, can you share any videos of kazati not working?

**Comment by ToxicSSJ** [comment]
Kazati is working fine.
