### ISSUE TITLE
Bug extraño en la creacion de flotas

### ISSUE THREAD

**Issue by Monchoplay** [SuperGO2/supergo2-issues#433]
**Describe el bug**
De la nada, cuando creas una flota, se crea con otro cc y es ineditable, esto permanece asi hasta que de manera aleatoria se pone el cc con el cual creaste la flota.
**Como reproducirlo**
al parecer al entrar y salir de instancias, intentar crear flotas una y otra vez hasta que se produce, pero no lo se reproducir de forma exacta, tiene que ser al parecer un problema con el registro de acciones en el juego.
1. abrir creacion de flotas, 
2. seleccionar un cc aleatorio y poner las naves
3. cerrar creacion de flotas, intentar ponerles he3, confirmar la recarga de gas, cerrar la carga de gas.
3. la flota se frezea, no carga gas, aparece un cc aleatorio al cc que pusiste y no te permite realizar acciones en cuanto a esa u otra flota al intentar cargarles gas

**Comportamiento esperado**
deberia actuar con normalidad, crear la flota sin problema, ponerle gas y confirmar para realizar acciones con ella

**Imágenes**

**Información Adicional**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2010b.closed-alpha` version.
