### ISSUE TITLE
Naves

### ISSUE THREAD

**Issue by sparta-1** [SuperGO2/supergo2-issues#434]
**Describe el bug**
Buenos dias Toxic, tengo una dificultad en el juego, se me desaparecieron naves del mercado que subí en pc hace unas 2 horas mas o menos, y cuando quiero crear flotas no me aparecen las naves tengo que volver a cargar aveces me salen otras veces no, si puedes ayudarme te agradeceria, gracias por tu tiempo, Soy Sparta ID:677

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Abrir el catalogo
2. Comprar algo
3. Cerrar el catalogo
3. Ver el error.

**Comportamiento esperado**
Al cerrar el catalogo no debería salir ningún error.

**Imágenes**
Aquí agregaré enlaces a imagenes/video o también puedo arrastrar el contenido.

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by ToxicSSJ** [comment]
Por favor use el formato correcto para reportar incidencias.
