### ISSUE TITLE
Problema con creacion de flotas

### ISSUE THREAD

**Issue by nachoroas** [SuperGO2/supergo2-issues#435]
**Describe el bug**
Al crear flotas una se crea con el cc de otra persona lo que la hace ineditable e inutilizable
**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Crear una serie de flotas consecutivamente
2. Ir a la base espacial luego de confirmar
3. Al poner el mouse encima de las flotas una tiene un cc de otra persona

**Comportamiento esperado**
Las flotas deberían tener los comandantes que se les asigno

**Imágenes**
**Información Adicional**

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2010b.closed-alpha` version.
