### ISSUE TITLE
Ship specs bug in Auction

### ISSUE THREAD

**Issue by GodValley25** [SuperGO2/supergo2-issues#439]
**Describe the bug**
This bug makes everyships that i sell look different and so annoying when try to sell ships

**To Reproduce**
1. Go to 'Auction'
2. Click on Selling you will see the ships you sell have a bug 
3. Click on ships table on Purchase and you will see your ships have diffrent specs from what you make

**Expected behavior**
Please fix this ASAP i need to have mp income but the auction trolled me -_-

**Screenshots**
![jl;;](https://user-images.githubusercontent.com/115976308/196940167-b3c0c32d-8a4f-4eb3-8861-126d2fa2ecde.PNG)
![image](https://user-images.githubusercontent.com/115976308/196940332-e854c89f-9b43-4d03-841b-5f912092225d.png)

And not just me every people post after the action update have the same problem

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2110a.closed-alpha` version.
