### ISSUE TITLE
I am unable to login to my account

### ISSUE THREAD

**Issue by Jestorick** [SuperGO2/supergo2-issues#441]
**Describe el bug**
Una descripción clara y concisa de que hace el bug.

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Abrir el catalogo
2. Comprar algo
3. Cerrar el catalogo
3. Ver el error.

**Comportamiento esperado**
Al cerrar el catalogo no debería salir ningún error.

**Imágenes**
Aquí agregaré enlaces a imagenes/video o también puedo arrastrar el contenido.

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by ToxicSSJ** [comment]
Please follow the format.

**Comment by Jestorick** [comment]
ok

**Comment by Jestorick** [comment]
I don't speak spanish
