### ISSUE TITLE
Iron veil bugs

### ISSUE THREAD

**Issue by GodValley25** [SuperGO2/supergo2-issues#443]
**Describe the bug**
The damage of iron veil III just stuck at 1048000. On 3000 ships/slot the damage supposed to be 500x3000=1500000

**To Reproduce**
1. Go to any fight with ships installed Iron Veil 3 and do 3k/slot fleet.
2. You'll see the reflect dmg just stuck at 1048000

**Expected behavior**
Its supposed to be 1.5m reflect dmg and it'll help a lot when do anything. I hope you can fix this problem too  Toxic ASAP.

**Screenshots**
![image](https://user-images.githubusercontent.com/115976308/197237541-1a4b80a4-80bf-4991-92e1-146b55c0105d.png)

Thanks for always do the work.

**Comment by 0Nimroth** [comment]
But you are using a 7* commander, effective stacksize matters for iron veil and would only activate from around 2100 of the ships in this case.

**Comment by GodValley25** [comment]
> But you are using a 7* commander, effective stacksize matters for iron veil and would only activate from around 2100 of the ships in this case.

**Comment by GodValley25** [comment]
Ohh yes i tested with diff cc and the reflect dmg its diff too. Idk about about effective stacksize on iron veil honestly.
But guess im the one wrong. Thx for ur reply and new info

**Comment by ToxicSSJ** [comment]
You have to take into account the effective stack. You can check it in [https://krtools.deajae.co.uk/cc/](krtools).
