### ISSUE TITLE
Galaxy missclic

### ISSUE THREAD

**Issue by AngleEarth** [SuperGO2/supergo2-issues#445]
**Describe the bug**
When i went to the galaxy to attack another player or an Humaroid planet, i can't select it.  Even my own planet can't be selected.

**To Reproduce**
1. Click on Space base
2. Click on Galaxy
3. Scroll to find other planet
4. Click on those planet
5. Sometime you will see error and other time you will see the planet menu

**Expected behavior**

Every time i click on a planet, i should be able to see the planet menu.

**Screenshots**
<img width="485" alt="Capture d’écran 2022-10-21 200332" src="https://user-images.githubusercontent.com/116408766/197306729-5fcacb35-7ba0-4e0d-b83a-11515a3fe8e1.png">

**Additional context**

**Comment by ToxicSSJ** [comment]
This is an old client error. Can't be fixed.
