### ISSUE TITLE
Speed UP ships building

### ISSUE THREAD

**Issue by Rcuison** [SuperGO2/supergo2-issues#446]
**Describe the bug**
I just spent 40mp for speed up shipbuilding but still the shipbuilding center do not give me the ships after speeding up

**To Reproduce**
1. Go to 'Build'
2. Click on 'Build Warships'
3. Speed up the time building 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/116321500/197308175-97c94263-c7c7-4548-a8aa-53b86e179157.png)

**Comment by Tuni67** [comment]
I dont get it. Seems to be working fine. Your ships are building faster, you dont get the ships instantly xd

**Comment by ToxicSSJ** [comment]
As @Tuni67 said, it only speeds up the ships building time.
