### ISSUE TITLE
Corp Donations null

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#45]
Description: Donating to corp with overflowing resources fucks it up
How to reproduce: get overflowing resources and donate to corp (i was donating 400 mill gold but 500 gold was actually getting removed+contribution score went to negative
Expected behavior: game should boot you back to normal resources and then the donation system should work

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
