### ISSUE TITLE
auction searching not working

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#476]
**Describe the bug**
auction searching not working 100% when u search for an item its not showing all 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment]
A lot of information is missing, you imply that the search doesn't work but it does. You must be more specific, I suppose it is a duplicate of not being able to search for cards from other stars.
