### ISSUE TITLE
nao entendi o jogo e criei 3 contas dai fiquei sabendo que nao poderia ter feito so quero voltar a jogar fui bloqueado

### ISSUE THREAD

**Issue by maxmountain12** [SuperGO2/supergo2-issues#478]
**Describe el bug**
Una descripción clara y concisa de que hace el bug.

**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Abrir el catalogo
2. Comprar algo
3. Cerrar el catalogo
3. Ver el error.

**Comportamiento esperado**
Al cerrar el catalogo no debería salir ningún error.

**Imágenes**
Aquí agregaré enlaces a imagenes/video o también puedo arrastrar el contenido.

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by ToxicSSJ** [comment]
This is not the place for report this, you have to open a ticket in discord.
