### ISSUE TITLE
SPEED UP SHIP BUILDING

### ISSUE THREAD

**Issue by Rcuison** [SuperGO2/supergo2-issues#496]
![image](https://user-images.githubusercontent.com/116321500/200227247-a384390a-61e6-480e-982a-9027a97b6b38.png)

Hi Guys!

Can you fix this bug? Looks like speed up ship building has a bug.

Will be looking for replies, thanks!

**Comment by whoisrry** [comment]
no description, no steps to reproduce
....
;((

**Comment by Rcuison** [comment]
Are you guys not playing? Why do you guys not know how to produce a ship xD

**Comment by ToxicSSJ** [comment]
Please use the right format.
