### ISSUE TITLE
Overflowing resources

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#5]
Description: Overflowing resources breaks multiple things (will continue to list different stuff here)
How to reproduce: go over 2,5 billion in any resource
Expected behavior: game is supposed to fix back to 999 mill resources
![image](https://user-images.githubusercontent.com/102363858/160247008-6cdf513b-aabb-41ed-8931-b497f2f9d172.png)
![image](https://user-images.githubusercontent.com/102363858/160247013-06d73868-016c-42e7-9f86-ebd56f464917.png)

**Comment by Accone** [comment]
2. Building ships while overflowing resources makes that all shipbuilding doesnt take the resources away

**Comment by Accone** [comment]
3. You cant donate to corps while having overflowing resources

**Comment by Accone** [comment]
4. You cant build buildings while overflowing resources?

**Comment by ToxicSSJ** [comment]
This bug was fixed `V2022.35b.beta-dev`.
