### ISSUE TITLE
LT.Cols in corp dont have the correct "rights"

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#50]
Description: Lt.Cols should be able to do everything else what the col can, except upgrade the corp or kick other LTs/Col

**Comment by Accone** [comment]
i suspect the COS rank is wrong as well then but i havent tested it.
Cos rank should be able to recruit players into the corp

**Comment by Accone** [comment]
Elite rank can send to rbps
Recruit cant do anything

**Comment by spectuu** [comment]
Done!

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
