### ISSUE TITLE
Fleets missing after creation

### ISSUE THREAD

**Issue by whoisrry** [SuperGO2/supergo2-issues#500]
**Describe the bug**
The ships missing after creation, i selected commanders and put the fleets up. but not showing, i tried to relogin, but no help

**To Reproduce**
1. Create a fleet with Dullahan (3k for each 7 slot, Zefram-MK24-III (3k for 1 slot), and Abyssal Syclla-II (50 for 1 slot)
2. Choose commander
3. Set max attack power
4. The fleets not showing on space station
5. I cannot dismiss or send the fleet to other planet (when i click send)
6. All the ships on that fleet went missing (number decreased)

**Expected behavior**
The fleet should be on space station, and can be dismissed

**Screenshots**

**Additional context**

**Comment by whoisrry** [comment]
https://youtu.be/rxqAPvBcleY
This is how i reproduced the bug
It really went missing

**Comment by whoisrry** [comment]
https://youtu.be/a7qoCtYPzj0

i recorded a video how to reproduce it
i'm not sure how, but:
Dullahan "DD-HBI-400CC" was 14k before, now it's only 6k. missing 8k(before bug reproduce)
Dullahan "DD-BHX-480CC" was around 90k before, now only 73k. missing 17k (before bug reproduce)
Zefram-MK24-III "JK-FIII-450CC" was 7k before, it's only 1k left. missing 6k (before bug reproduce)
Abyssal-II "Blanks" was 200, now only 100. missing 100 (before bug reproduce)
the thing is, they went missing when i modify a fleet with dullahans in it
And...
They're all gone xD

**Comment by StarfishPrime-1** [comment]
Can you link the Dullahan design?

**Comment by RockandTroll** [comment]
Sorry to pile on but I don't want to open a new ticket for it

Looks like its because of multiple flagships, I was able to replicate by using Scylla and Kazati, if you add both ships into a fleet, the fleet creation fails because you have multiple flagships in it.

But instead of giving the ships back, they just disappear.

See video for example:
https://www.youtube.com/watch?v=0uIhZAu2-i0

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2811a.closed-alpha` version.
