### ISSUE TITLE
Cuenta baneada

### ISSUE THREAD

**Issue by NicolasdelasCasasMaldini** [SuperGO2/supergo2-issues#504]
**Describe el bug**
Una descripción clara y concisa de que hace el bug.
me banearon sin ningun sustento mi primo creo una cuenta estamos en la misma red/casa/ip lo mismo pero me banearon pq de el tenia un problema su cuenta se duplico y no tenia como reportarlo por favor solucion "NicolasDeLasCasasMaldini".
**Como reproducirlo**
Pasos para replicar el bug siga estos pasos:
1. Abrir el catalogo
2. Comprar algo
3. Cerrar el catalogo
3. Ver el error.

**Comportamiento esperado**
Al cerrar el catalogo no debería salir ningún error
**Imágenes**
Aquí agregaré enlaces a imagenes/video o también puedo arrastrar el contenido.

**Información Adicional**
Aquí debo agregar información adicional del bug.

**Comment by NicolasdelasCasasMaldini** [comment]
![image](https://user-images.githubusercontent.com/118084927/201499887-ab06ab8b-3251-471d-9320-9f88d71f3d13.png)
![image](https://user-images.githubusercontent.com/118084927/201499890-603e5ff7-b867-4421-b244-c88cf5485ace.png)

**Comment by ToxicSSJ** [comment]
This is not the place for this.

**Comment by NicolasdelasCasasMaldini** [comment]
Entonces cuando me habilitan?
