### ISSUE TITLE
account suspension

### ISSUE THREAD

**Issue by Dsd006** [SuperGO2/supergo2-issues#510]
Good afternoon, how are you? I wanted to ask you about the problem of multiple accounts, I was banned for using accounts in two different operating systems in the same house? I mean, only one person is authorized to use the account? Or were they banned for using the account on the same computer? I have nephews and I'm teaching them what the game is but they don't have an email address. I've been playing this for 25 years since I was 13. I have to teach my generation what a great game is and I end up with a been... now if that's the case, you can't Will it be permanent or is it only until the reset? I would like to know, if such a case of knowing more I would like you to publish the PC purchase pages if it is paypal or another payment method I am from Venezuela and well, never in my life could I put money into the game, but I hope that this time it will be different

**Comment by Tuni67** [comment]
Open a Ticket on Discord. The GitHub is only for game related bugs.
