### ISSUE TITLE
Humaroid 2 movement of ship based fleet

### ISSUE THREAD

**Issue by anon-1800** [SuperGO2/supergo2-issues#523]
**Describe the bug**
According to krtools the movement of the ship based fleet on Humaroid 2 should be 4, when it it's at least 7. 
**To Reproduce**
1. Send a fleet that can do huma2 with 7 movement to a Humaroid lv.2
2. Let the fleet destroy all the other fleets.
3. Watch how the ship based fleet moves more than 4 spaces and your fleet never catching up with it.

**Expected behavior**
The fleet with ship based weapons shouldn't move more than 4 spaces.

**Comment by 0Nimroth** [comment]
This isn't a bug, krtools isn't counting the added movement from the mercury wing flagship that all the fleets in humaroid 2 have.

**Comment by anon-1800** [comment]
My bad, forgot about the flagships.
