### ISSUE TITLE
can not log in server

### ISSUE THREAD

**Issue by 7621119** [SuperGO2/supergo2-issues#528]
i can not log in server even using normal supergo2.exe or auto instance farming

i do not use VPN or proxy or anything affect to my connection

![image](https://user-images.githubusercontent.com/118913893/204236510-b5374f92-c98d-4662-942b-677ad048a27f.png)

![image](https://user-images.githubusercontent.com/118913893/204236854-9eb90e00-cc5e-451e-b714-9a5f064e8bda.png)

![image](https://user-images.githubusercontent.com/118913893/204237218-74bebf54-822c-4dfa-87cc-a833a3a4260f.png)

![image](https://user-images.githubusercontent.com/118913893/204238036-544b496e-651a-4c4b-917d-688f7045381d.png)

Solution: login with browser on my phone

**Comment by 7621119** [comment]
hello, my account has been suspended, could we talk.
![image](https://user-images.githubusercontent.com/118913893/204338243-f1499ea1-c4ea-47f8-a5c1-cc675c72e96d.png)

**Comment by ToxicSSJ** [comment]
Hello, this is not the place for this and you are not using the right format, you have to open a ticket through our discord.
