### ISSUE TITLE
Quest rewards are broken

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#56]
Description: Quest rewards are giving incorrect amounts, for example a quest what was supposed to give 800 gold gave 500, and a quest what was supposed to give 3k gave 1k

**Comment by Accone** [comment]
You cannot advance in directional tech because of this (you get magneto pulsar from a repeatable quest)

**Comment by ToxicSSJ** [comment]
Partially resolved in `V2022.3006c.beta-dev` version.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0307a.closed-alpha` version.
