### ISSUE TITLE
Something is still wrong in targeting

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#59]
Description: Some targets dont function as intended (closest is only one tested) The target "sticks" to a fleet when it is supposed to change each round

**Comment by Accone** [comment]
![2022-06-30 (4)](https://user-images.githubusercontent.com/102363858/176761812-6671619e-d3aa-40d3-9973-e8dea3124227.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
