### ISSUE TITLE
Linking comms

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#6]
Description: Linking comms in chat doesnt show gems/other stuff
How to reproduce: put gems on comms and link in chat
Expected behavior: all gems and chips should be visible on the linked chat
![image](https://user-images.githubusercontent.com/102363858/160247126-88768d0d-8475-45de-a47b-b1afcfe5591e.png)
![image](https://user-images.githubusercontent.com/102363858/160247129-7ff386ba-2f0a-4dca-ac82-dd8932744732.png)

**Comment by spectuu** [comment]
Done!
