### ISSUE TITLE
Wrong commander info 

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#60]
Description: For some reason, the fleet selector screen shows old info of a commander
![2022-06-30 (1)](https://user-images.githubusercontent.com/102363858/176673705-3ff5f420-ede2-4aea-a7bc-df2e244cba8a.png)
![2022-06-30 (2)](https://user-images.githubusercontent.com/102363858/176673813-211cec10-6c88-441d-b928-3bcaa7fb23c0.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.2307b.closed-alpha` version.
