### ISSUE TITLE
Trading volume quest doesnt work?

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#64]
Description: There is a repeatable quest for something called "trading volume" but the quest doesnt complete when you actually trade in the trading centre (even though that is "trading volume"?)

**Comment by StarfishPrime-1** [comment]
Similar Issue for me as well But I cannot complete it at all despite buying and selling

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0507b.closed-alpha` version.
