### ISSUE TITLE
I keep getting Taskmaster blueprint

### ISSUE THREAD

**Issue by ABanC1001** [SuperGO2/supergo2-issues#65]
I was waiting for the 2nd laser blueprint but I just got taskmaster, I have the blueprint already investigated but I have 5 more :
![eISE9lJ](https://user-images.githubusercontent.com/108493836/176777551-ca6dfc4b-0510-42ec-8fd9-b9b7b5b764fd.png)
/

**Comment by ABanC1001** [comment]
And that's not all, I cant use the laser weapons because I cant get the Magneto Pulsar

**Comment by ToxicSSJ** [comment]
This is duplicate of #56.
