### ISSUE TITLE
Insta-Reloading enemies

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#67]
Description: In a instance if a enemy fleet manages to kill you using only half of their shooting stacks (for example a fleet with 9 stacks using 4 to kill yours) thus leaving 5 more stacks to shoot next round and 4 stacks to reload logically
Currently what happens is that the 4 stacks what shot the previous round instareload to shoot with the rest

**Comment by ToxicSSJ** [comment]
@Accone This issue maybe have been resolved with `V2022.0407a.closed-alpha`. Can you check?

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0507b.closed-alpha` version.
