### ISSUE TITLE
Resource harvesting

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#7]
Description: Cant harvest all of the resources for some reason
How to reproduce: fill all slots and try to harvest them in the same time?
Expected behavior: supposed to get all resources
![image](https://user-images.githubusercontent.com/102363858/160247856-0aaff584-8210-469f-ba1e-209c09e00e7a.png)

**Comment by Accone** [comment]
was caused by no sp, but isnt the sp cost  only when you harvest from other people?

**Comment by ToxicSSJ** [comment]
> was caused by no sp, but isnt the sp cost only when you harvest from other people?

you are right, i'll fix that

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.514b.beta-dev` version.
