### ISSUE TITLE
Tech missile research issue

### ISSUE THREAD

**Issue by Zacmadness** [SuperGO2/supergo2-issues#72]
#Bug
How to produce: start the level 10 of missiles theory in tech
When you start the research level 10 of missiles theory it consume you 10k of gold instead the 18k and not start the research, just happen nothing I tried 2 time and still consume my gold but not start 
![Screenshot_2022-07-01-06-52-35-202_com cloudmosa puffinFree](https://user-images.githubusercontent.com/108496089/176881625-0d02d3e5-9233-4a66-826c-936b04e11338.jpg)

**Comment by ToxicSSJ** [comment]
Can't reproduce.
