### ISSUE TITLE
Building get bugged

### ISSUE THREAD

**Issue by ABanC1001** [SuperGO2/supergo2-issues#77]
Description: Updating a build in a row (I did it with 4 resident areas quickly in a row) buges your resources, and you have to restart the game and the resources get resetted (in my case, I went from 50k gold to 7k gold) and the update doesn't start.

How to replicate: I did it with 4 resident areas quickly in a row from lvl 9 to 10, the last resident area didn't start and my gold didn't change but when I reload the game the gold resseted from before the updates.

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.1008a.closed-alpha` version.
