### ISSUE TITLE
Help i clicked buttons and my planet became a star

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#8]
Description:my planet became a star
How to reproduce: use 18998 gaseous planets
Expected behavior: planet is not supposed to become a star 
https://youtu.be/lCciCBn4F3A

**Comment by irtusb** [comment]
this happened sometimes in original. In specific situation you can spam _galaxy button_ and will stack the border seen in video

**Comment by ToxicSSJ** [comment]
I'm pretty sure it's a client error.

**Comment by ToxicSSJ** [comment]
Client error.
