### ISSUE TITLE
Lucky wheel don't work with the MVP tool active

### ISSUE THREAD

**Issue by Zacmadness** [SuperGO2/supergo2-issues#80]
#bug
How to produce: use a MVP tool and try spin the lucky wheel

After use the MVP tool and spin the 2 extra free attempt the lucky don't work and the menu get freeze 
![Screenshot_2022-07-02-04-21-48-654_com cloudmosa puffinFree](https://user-images.githubusercontent.com/108496089/176993097-39ec49da-a0d9-4e5f-9c5a-eab2dc863bdd.jpg)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0407a.closed-alpha` version.
