### ISSUE TITLE
Space station just show 10 friends 

### ISSUE THREAD

**Issue by Zacmadness** [SuperGO2/supergo2-issues#81]
#bug
How to produce: add more than 10 friends and enter to the space station

In your friend list you can see all friends that you add but going to the space station only will show 10 
![Screenshot_2022-07-02-07-39-46-556_com cloudmosa puffinFree](https://user-images.githubusercontent.com/108496089/176999363-4cffe720-5900-4072-99da-9e21b8e0d191.jpg)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0407a.closed-alpha` version.
