### ISSUE TITLE
Moving buildings create duplicates

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#82]
Description: If you move buildings the original building will still remain in place, thus creating a working double of it. Bug got triggered in the same time as  MSG_RESP_BUILDCOMPLETE packet got missing (not confirmed if this was a actual cause, or just a coincidence)

**Comment by ToxicSSJ** [comment]
This bug could have been resolved with #112. @Accone Can u confirm?

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
