### ISSUE TITLE
Vouchers in Lucky well gives the wrong ammount

### ISSUE THREAD

**Issue by ABanC1001** [SuperGO2/supergo2-issues#84]
Description: Getting vouchers in lucky well gives like 500 vouchers instead of 300 that is shown there.
How to replicate: Just get vouchers there

**Comment by ToxicSSJ** [comment]
Can't reproduce. Are you sure?

**Comment by ABanC1001** [comment]
Yes, I saw it but im sure it was just visual

**Comment by ToxicSSJ** [comment]
Issue resolved. This never actually happens, most likely it was a lag visual error.
