### ISSUE TITLE
Newly created Fleet appears in Instance map while doing an Instance

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#88]
Newly created Fleet appears in Instance map

**To Reproduce**
1. Start a Instance with 2 Fleets
2. Click on "Create Fleet" and create a third fleet
3. Look at Instance map
4. See a third fleet appear

**Expected behavior**
The third fleet doesnt appear in Instance map

![screen2](https://user-images.githubusercontent.com/108492773/177132058-5e83339c-9106-48d6-969b-ab33d4ce3071.JPG)
![screen3](https://user-images.githubusercontent.com/108492773/177132061-4f991124-0595-4fcb-8d59-877534a6101b.JPG)
![Screen1](https://user-images.githubusercontent.com/108492773/177132052-4ff92c71-f91f-4466-86f8-ce11c4d2bf6f.JPG)

**Comment by Tuni67** [comment]
Third picture is the first picture

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0407a.closed-alpha` version.
