### ISSUE TITLE
Fleets magically disappearing from instance after getting hit by missile instance fleet.(without taking damage)

### ISSUE THREAD

**Issue by skyprime17** [SuperGO2/supergo2-issues#89]
**Description**
Fleets disappearing from instance after getting hit by missile instance fleet.(without taking damage)

**To Reproduce**
1. Start an instance where enemy has missile fleets(instance 6 in this video)

**Screenshots**
https://user-images.githubusercontent.com/57846375/177190808-4171caef-aead-4b4c-b3c9-be7417fff13b.mp4

**Comment by Tuni67** [comment]
Had the same issue, it happend when my fleet was hit from behind.

**Comment by skyprime17** [comment]
Perhaps theres no validation for the stability ? When fleets get hit from behind,they lose stability

**Comment by ToxicSSJ** [comment]
I think this is a duplicate of #74.

**Comment by Tuni67** [comment]
Looks like it

**Comment by skyprime17** [comment]
@ToxicSSJ is it tho? Im talking about the fleet disappearing from the  instance, its gone

**Comment by ToxicSSJ** [comment]
@skyprime17 Probably, because the bug consists in negative stability when the ships are attacking to the rear. So I think this should be fixed when that issue gets fixed.

**Comment by ToxicSSJ** [comment]
@skyprime17 This issue maybe have been resolved with `V2022.0407a.closed-alpha`. Can you check?

**Comment by skyprime17** [comment]
Seems to be fixed,yep

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0507b.closed-alpha` version.
