### ISSUE TITLE
Science. Construction boost 1/10 research time

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#91]
Construction boost 1/10 research time should be 14:47min  but is infact 14.47 seconds
<img width="535" alt="14sec" src="https://user-images.githubusercontent.com/102439239/177210585-5bbf7c59-6176-49e3-8255-8b8685ff9d8f.png">

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0407a.closed-alpha` version.
