### ISSUE TITLE
EZ rewards issue

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#93]
**Describe the bug**
after you open the account ,  EZ rewards ready to be claimed , after clicking claim , **you get nothing** then the icon disappear , it comes again once you reopen the game , then again claim nothing. 

**Expected behavior**
should be claimable with countdown timer 

**Screenshots**

![ez rewards](https://user-images.githubusercontent.com/108695969/177231750-8ffab28e-cb6d-47f2-9e68-cc1d082830b3.png)

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0407a.closed-alpha` version.
