### ISSUE TITLE
Bionic chips slots are close

### ISSUE THREAD

**Issue by Colorap8** [SuperGO2/supergo2-issues#94]
**Describe the bug**
you cant generate chips because all the cells are close

**To Reproduce**
1. Go to "generate bionic chips"
2. Click on "auto generate"
3.  'all chips slots are full'

**Expected behavior**
Open the slots and make some chips :(((

**Comment by ToxicSSJ** [comment]
Resolved in `V2022.0807a.closed-alpha` version.
