### ISSUE TITLE
Ship Building cancelling 

### ISSUE THREAD

**Issue by ABanC1001** [SuperGO2/supergo2-issues#99]
**Describe the bug**
If you cancel the ship building it will not give you the resources back.

**To Reproduce**
1. Go to Ship factory
2. Click on "build ship" and then "cancel ship build"
3. See error

**Comment by ToxicSSJ** [comment]
Can't reproduce this.

**Comment by ToxicSSJ** [comment]
Issue resolved. This never actually happens, cancelling a ship queue will return you a 10% of the remaining resources.
